import { NextRequest, NextResponse } from "next/server";
import ExcelJS from "exceljs";
import { getSession } from "@/lib/auth";
import { ensureTalentSeed } from "@/lib/talent-seed";
import { getTalentData } from "@/lib/talent-data";
import { stages } from "@/lib/talent-types";
export async function GET(request: NextRequest) {
  const user = await getSession(); if (!user) return NextResponse.json({ error: "ورود لازم است." }, { status: 401 }); await ensureTalentSeed(); const data = await getTalentData(user); const kind = request.nextUrl.searchParams.get("type") || "recruitment";
  if (kind === "calendar") { const i = data.interviews.find(i => i.id === request.nextUrl.searchParams.get("id")); if (!i) return NextResponse.json({ error: "جلسه در دسترس نیست." }, { status: 404 }); const c = data.applicants.find(c => c.id === i.applicantId); const stamp = (date: Date) => date.toISOString().replace(/[-:]/g, "").replace(/\.\d+Z$/, "Z"); const escape = (s: string) => s.replace(/\\/g, "\\\\").replace(/\r?\n/g, "\\n").replace(/[,;]/g, " "); const content = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//Aban HR//Interview//FA", "BEGIN:VEVENT", `UID:${i.id}@aban`, `DTSTAMP:${stamp(new Date())}`, `DTSTART:${stamp(new Date(i.startsAt))}`, `DTEND:${stamp(new Date(Date.parse(i.startsAt) + i.duration * 60000))}`, `SUMMARY:${escape(`مصاحبه ${c?.name || ""}`)}`, `LOCATION:${escape(i.location)}`, "END:VEVENT", "END:VCALENDAR"].join("\r\n"); return new Response(content, { headers: { "Content-Type": "text/calendar; charset=utf-8", "Content-Disposition": 'attachment; filename="interview.ics"', "Cache-Control": "no-store" } }); }
  if (kind === "recruitment" && !["admin", "manager"].includes(user.role) || kind === "compensation" && !["admin", "finance"].includes(user.role) || kind === "pulse" && !["admin", "manager"].includes(user.role)) return NextResponse.json({ error: "دسترسی کافی ندارید." }, { status: 403 });
  const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet("گزارش آبان", { views: [{ rightToLeft: true, state: "frozen", ySplit: 1 }] });
  if (kind === "recruitment") { sheet.addRow(["نام متقاضی", "ایمیل", "فرصت شغلی", "منبع", "مرحله", "امتیاز", "سابقه", "تاریخ ثبت"]); data.applicants.forEach(c => sheet.addRow([c.name, c.email, data.jobs.find(j => j.id === c.jobId)?.title || "", c.source, stages.find(s => s.id === c.stage)?.label || c.stage, c.rating, c.experience, c.createdAt.slice(0, 10)])); }
  else if (kind === "learning") { sheet.addRow(["شناسه کارمند", "دوره", "وضعیت", "درس تکمیل‌شده", "نمره", "مهلت"]); data.enrollments.forEach(e => sheet.addRow([e.employeeId, data.courses.find(c => c.id === e.courseId)?.title || "بایگانی‌شده", e.status, e.completedLessons.length, e.score, e.dueDate])); }
  else if (kind === "compensation") { const scenario = data.scenarios.find(s => s.id === request.nextUrl.searchParams.get("id")); if (!scenario) return NextResponse.json({ error: "سناریو را انتخاب کنید." }, { status: 404 }); sheet.addRow(["کد", "نام", "واحد", "حقوق فعلی", "حقوق پیشنهادی", "تغییر", "وضعیت سناریو"]); scenario.entries.forEach(e => sheet.addRow([e.code, e.name, e.department, e.current, e.proposed, e.proposed - e.current, scenario.status])); }
  else if (kind === "pulse") { sheet.addRow(["نظرسنجی", "شاخص", "امتیاز درصدی", "تعداد پاسخ"]); data.metrics.filter(m => m.reportReady).forEach(m => m.dimensions.forEach(d => sheet.addRow([data.surveys.find(s => s.id === m.surveyId)?.title || "", d.title, d.percent, m.responses]))); }
  else return NextResponse.json({ error: "گزارش نامعتبر است." }, { status: 400 });
  sheet.columns.forEach(c => c.width = 27); sheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; sheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF129D96" } }; const buffer = await book.xlsx.writeBuffer(); return new Response(new Uint8Array(buffer), { headers: { "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Content-Disposition": `attachment; filename="aban-${kind}.xlsx"`, "Cache-Control": "private, no-store" } });
}
