import { NextRequest, NextResponse } from "next/server";
import { eq, and } from "drizzle-orm";
import { db } from "@/db";
import { resumeFiles, applicants, jobs } from "@/db/schema";
import { getSession, checkOrigin } from "@/lib/auth";
import { talentScope } from "@/lib/talent-data";
import { validateResume } from "@/lib/resume";
import { id, fail, TalentError } from "@/lib/talent-validation";
async function authorize(applicantId: string) { const user = await getSession(); if (!user || !["admin", "manager"].includes(user.role)) return fail("دسترسی تیم جذب لازم است.", 403); const scope = await talentScope(user); const [candidate] = await db.select({ id: applicants.id, department: jobs.department }).from(applicants).innerJoin(jobs, eq(jobs.id, applicants.jobId)).where(eq(applicants.id, applicantId)); if (!candidate || user.role !== "admin" && candidate.department !== scope.department) return fail("پیوست در دسترس نیست.", 404); return user; }
function errorResponse(e: unknown) { return NextResponse.json({ error: e instanceof TalentError ? e.message : "عملیات فایل انجام نشد." }, { status: e instanceof TalentError ? e.status : 500 }); }
export async function GET(request: NextRequest) { try { const [meta] = await db.select({ applicantId: resumeFiles.applicantId }).from(resumeFiles).where(eq(resumeFiles.id, id(request.nextUrl.searchParams.get("id")))); if (!meta) fail("فایل پیدا نشد.", 404); await authorize(meta.applicantId); const [file] = await db.select().from(resumeFiles).where(eq(resumeFiles.id, id(request.nextUrl.searchParams.get("id")))); return new Response(new Uint8Array(Buffer.from(file.content, "base64")), { headers: { "Content-Type": "application/pdf", "Content-Disposition": `attachment; filename="resume.pdf"; filename*=UTF-8''${encodeURIComponent(file.name)}`, "X-Content-Type-Options": "nosniff", "Content-Security-Policy": "sandbox", "Cache-Control": "private, no-store" } }); } catch (e) { return errorResponse(e); } }
export async function POST(request: NextRequest) { if (!checkOrigin(request)) return NextResponse.json({ error: "مبدأ نامعتبر" }, { status: 403 }); try { if (Number(request.headers.get("content-length")) > 3 * 1024 * 1024) fail("حجم فایل زیاد است.", 413); const form = await request.formData(); const applicantId = id(form.get("applicantId")); await authorize(applicantId); const file = await validateResume(form.get("file")); if (!file) fail("یک فایل انتخاب کنید."); const existing = await db.select({ id: resumeFiles.id }).from(resumeFiles).where(eq(resumeFiles.applicantId, applicantId)); if (existing.length >= 5) fail("حداکثر پنج پیوست برای هر متقاضی مجاز است."); const [saved] = await db.insert(resumeFiles).values({ ...file!, applicantId }).returning({ id: resumeFiles.id }); return NextResponse.json({ ok: true, id: saved.id }); } catch (e) { return errorResponse(e); } }
export async function DELETE(request: NextRequest) { if (!checkOrigin(request)) return NextResponse.json({ error: "مبدأ نامعتبر" }, { status: 403 }); try { const fileId = id(request.nextUrl.searchParams.get("id")); const [file] = await db.select({ applicantId: resumeFiles.applicantId }).from(resumeFiles).where(eq(resumeFiles.id, fileId)); if (!file) fail("فایل پیدا نشد.", 404); await authorize(file.applicantId); await db.delete(resumeFiles).where(eq(resumeFiles.id, fileId)); return NextResponse.json({ ok: true }); } catch (e) { return errorResponse(e); } }
