import { randomUUID } from "node:crypto";
import { sql, eq } from "drizzle-orm";
import { db } from "@/db";
import { employees, jobs, applicants, applicantNotes, interviews, onboardingTemplates, onboardingPlans, onboardingTasks, courses, enrollments, surveys, surveyAudience, surveyResponses, improvements, salaryPolicies, talentVersions, talentEvents } from "@/db/schema";
import { departments } from "@/lib/types";
import { stages } from "@/lib/talent-types";
import { ensureSeed } from "@/lib/seed";
let preparing: Promise<void> | undefined;
export function ensureTalentSeed() { return preparing ||= seed().catch(error => { preparing = undefined; throw error; }); }
export const shiftDate = (days: number, start = new Date()) => new Date(start.getTime() + days * 86400000).toISOString().slice(0, 10);
async function seed() {
  await ensureSeed();
  await db.transaction(async tx => {
    await tx.execute(sql`select pg_advisory_xact_lock(827402)`);
    if ((await tx.select().from(talentVersions).where(eq(talentVersions.key, "talent-v1"))).length) return;
    const staff = await tx.select().from(employees).orderBy(employees.code);
    if (!staff.length) return;
    const sara = staff.find(e => e.email === "sara@aban.ir") || staff[0];
    const manager = staff.find(e => e.email === "manager@aban.ir") || staff[2] || staff[0];
    const titles = ["کارشناس نجات غریق", "کارشناس تجربه مهمان", "تکنسین تأسیسات", "کارشناس منابع انسانی", "حسابدار ارشد", "سرپرست خدمات"];
    const jobRows = titles.map((title, i) => ({ id: randomUUID(), title, department: departments[[0, 3, 4, 1, 2, 5][i]], location: "تهران · پارک آبی آبان", contract: i === 0 ? "شیفتی" : "تمام‌وقت", description: `برای تکمیل تیم ${title} در مجموعه آبان، به همکاری مسئولیت‌پذیر، دقیق و علاقه‌مند به کار تیمی نیاز داریم. محیطی پویا، آموزش بدو ورود و فرصت رشد در کنار همکاران باتجربه در انتظار شماست.`, requirements: "روحیه همکاری و ارتباط مؤثر\nتجربه مرتبط و تعهد به نظم کاری\nآمادگی برای کار در محیط خدماتی و رعایت دستورالعمل‌های مجموعه", status: i === 4 ? "draft" : "open", openings: [4, 3, 2, 1, 1, 2][i], salaryMin: 18000000 + i * 2000000, salaryMax: 29000000 + i * 3000000, hiringCost: 4000000 + i * 1500000, deadline: shiftDate(20 + i * 4), createdAt: new Date(Date.now() - (12 + i * 3) * 86400000) }));
    await tx.insert(jobs).values(jobRows);
    const names = ["نیلوفر کاظمی", "آرمان شریفی", "سحر نوری", "پرهام رضایی", "ریحانه امینی", "علی فرهمند", "مریم سعیدی", "کیان هاشمی", "نازنین توکلی", "رضا کریمی", "مهسا عباسی", "امیر فرهادی", "بهار صادقی", "پویان محمدی", "نرگس سلیمانی", "ماهان جعفری", "نگار رستمی", "بهرام زمانی"];
    const candidates = names.map((name, i) => ({ id: randomUUID(), jobId: jobRows[i % jobRows.length].id, name, email: `candidate${i + 1}@example.test`, phone: `0912555${String(1000 + i)}`, source: ["سایت مجموعه", "معرفی همکار", "جاب‌ویژن (ثبت دستی)", "شبکه‌های اجتماعی"][i % 4], tags: [i % 2 ? "باتجربه" : "اولویت بررسی", i % 3 ? "آماده همکاری" : "پاره‌وقت"], skills: "ارتباط مؤثر، کار تیمی، مسئولیت‌پذیری", experience: 1 + i % 6, expectedSalary: 21000000 + i % 7 * 2000000, stage: stages[[0, 0, 1, 2, 3, 1, 2, 5, 0][i % 9]].id, rating: i % 5, summary: "پرونده نمونه برای نمایش مسیر جذب؛ اطلاعات تماس آزمایشی است.", createdAt: new Date(Date.now() - (2 + i) * 86400000) }));
    await tx.insert(applicants).values(candidates);
    await tx.insert(applicantNotes).values(candidates.map((c, i) => ({ applicantId: c.id, actorName: "امیر محمدی", kind: "note", body: i % 2 ? "سوابق مرتبط بررسی شد؛ برای هماهنگی مصاحبه مناسب است." : "رزومه دریافت شد؛ بررسی شرایط احراز در صف تیم جذب است.", score: 0 })));
    await tx.insert(interviews).values([3, 6, 12].map((index, i) => ({ applicantId: candidates[index].id, interviewerId: manager.id, startsAt: new Date(`${shiftDate(i + 1)}T06:30:00Z`), duration: 45, mode: i === 1 ? "آنلاین" : "حضوری", location: i === 1 ? "لینک جلسه پس از هماهنگی ثبت می‌شود" : "اتاق جلسات منابع انسانی", status: "scheduled" })));
    const taskSpecs = [{ title: "مطالعه راهنمای خوش‌آمدگویی آبان", ownerRole: "employee", offsetDays: 0 }, { title: "تکمیل مدارک و اطلاعات پرسنلی", ownerRole: "employee", offsetDays: 1 }, { title: "تحویل تجهیزات و معرفی همیار", ownerRole: "admin", offsetDays: 1 }, { title: "آشنایی با تیم و برنامه شیفت‌ها", ownerRole: "manager", offsetDays: 2 }, { title: "شرکت در جلسه معارفه و فرهنگ آبان", ownerRole: "employee", offsetDays: 4 }, { title: "گفت‌وگوی پایان هفته اول", ownerRole: "manager", offsetDays: 7 }];
    const templateRows = [{ id: randomUUID(), title: "شروع همراهی در آبان", department: "all", welcome: "به خانواده آبان خوش آمدید 🌊\nاز امروز شما بخشی از جریان حال خوب مهمانان ما هستید. در روز اول به واحد منابع انسانی مراجعه کنید و با همیار خود آشنا شوید. برنامه هفته اول در همین صفحه قرار دارد. برای هر سؤال، مدیر واحد همراه شماست.\nساعات و محل حضور را با مدیر خود هماهنگ کنید. مطالعه دستورالعمل‌های اختصاصی شغلتان و آموزش زیر نظر مربی مجاز، پیش از شروع فعالیت عملی ضروری است.", tasks: taskSpecs }, { id: randomUUID(), title: "مسیر ورود تیم عملیات", department: departments[0], welcome: "به تیم عملیات آبان خوش آمدید. آشنایی با محیط، آموزش تخصصی زیر نظر مربی مجاز و تأیید آمادگی توسط سرپرست، پیش از فعالیت مستقل الزامی است.", tasks: [...taskSpecs, { title: "معرفی به مربی و برنامه آموزش تخصصی", ownerRole: "manager", offsetDays: 3 }] }];
    await tx.insert(onboardingTemplates).values(templateRows);
    const selectedStaff = [sara, ...staff.filter(e => e.id !== sara.id && e.status === "active").slice(0, 5)];
    for (const [index, e] of selectedStaff.entries()) { const template = templateRows[index % 2]; const startDate = shiftDate(-index - 1); const [plan] = await tx.insert(onboardingPlans).values({ templateId: template.id, employeeId: e.id, title: template.title, welcome: template.welcome, startDate }).returning(); await tx.insert(onboardingTasks).values(template.tasks.map((t, i) => ({ planId: plan.id, title: t.title, ownerRole: t.ownerRole, dueDate: shiftDate(t.offsetDays, new Date(startDate)), done: i < index % 4, completedBy: i < index % 4 ? "امیر محمدی" : "", completedAt: i < index % 4 ? new Date() : null }))); }
    const courseRows = [
      { id: randomUUID(), title: "فرهنگ آبان و تجربه مهمان", category: "فرهنگ سازمانی", instructor: "تیم منابع انسانی آبان", description: "شروع یک تجربه خوب، از رفتارهای کوچک ماست. در این مسیر با ارزش‌ها، ارتباط محترمانه و شیوه پیگیری درخواست مهمان آشنا می‌شوید.", level: "مقدماتی", status: "published", lessons: [{ id: "welcome", title: "ما در آبان چگونه همراه می‌شویم؟", content: "احترام، مسئولیت‌پذیری و همکاری سه اصل کار در آبان هستند. با مهمان و همکار محترمانه صحبت می‌کنیم، مسئولیت کار خود را می‌پذیریم و در موارد خارج از اختیار از سرپرست کمک می‌گیریم.", minutes: 10, url: "" }, { id: "guest", title: "شنیدن و پیگیری درخواست مهمان", content: "ابتدا بدون قطع صحبت به مهمان گوش بدهید. درخواست را دقیق ثبت کنید و در صورت نیاز به مسئول مربوط ارجاع دهید. قولی خارج از اختیار خود ندهید و تا روشن شدن نتیجه، پیگیری را ادامه دهید.", minutes: 15, url: "" }, { id: "team", title: "یک تیم، یک تجربه", content: "تحویل شیفت باید روشن و مستند باشد. کارهای باز را با همکار بعدی در میان بگذارید و اطلاعات حساس مهمانان را تنها با افراد مجاز به اشتراک بگذارید.", minutes: 10, url: "" }], quiz: [{ id: "q1", text: "اگر درخواست مهمان خارج از اختیار شما باشد چه می‌کنید؟", options: ["قول قطعی می‌دهم", "به مسئول مربوط ارجاع می‌دهم و پیگیری می‌کنم", "درخواست را نادیده می‌گیرم"], correct: 1 }, { id: "q2", text: "اطلاعات شخصی مهمان را با چه کسی می‌توان به اشتراک گذاشت؟", options: ["همه همکاران", "فقط افراد مجاز در چارچوب وظیفه", "شبکه‌های اجتماعی"], correct: 1 }], passScore: 70 },
      { id: randomUUID(), title: "حریم خصوصی و امنیت اطلاعات", category: "مهارت‌های عمومی", instructor: "واحد فناوری اطلاعات", description: "اصول حفاظت از حساب کاربری و اطلاعات شخصی کارکنان و مهمانان.", level: "مقدماتی", status: "published", lessons: [{ id: "security", title: "حفاظت از حساب و فایل‌ها", content: "رمز عبور را در اختیار دیگران نگذارید. فایل‌های پرسنلی فقط باید در سامانه مجاز نگهداری شوند. لینک‌های ناشناس را باز نکنید و هر دسترسی مشکوک را به واحد فناوری اطلاع دهید. هنگام ترک دستگاه مشترک از حساب خارج شوید.", minutes: 20, url: "" }], quiz: [{ id: "q1", text: "هنگام ترک یک دستگاه مشترک کدام کار ضروری است؟", options: ["خروج از حساب کاربری", "اشتراک‌گذاری رمز", "باز گذاشتن پرونده‌ها"], correct: 0 }], passScore: 70 },
      { id: randomUUID(), title: "هماهنگی شیفت و گزارش‌نویسی", category: "عملیات", instructor: "سرپرست عملیات", description: "ثبت شفاف کارهای باز، هماهنگی تغییر شیفت و پیگیری گزارش‌های روزانه.", level: "متوسط", status: "published", lessons: [{ id: "handover", title: "تحویل مسئولانه شیفت", content: "گزارش شیفت باید شامل کارهای انجام‌شده، موارد باز و نام مسئول پیگیری باشد. تغییر شیفت نیاز به تأیید سرپرست دارد. رویدادهای ایمنی را مطابق دستورالعمل رسمی مجموعه گزارش کنید؛ این متن جایگزین آموزش تخصصی نیست.", minutes: 25, url: "" }], quiz: [{ id: "q1", text: "گزارش تحویل شیفت باید چه چیزی را مشخص کند؟", options: ["فقط ساعت خروج", "موارد باز و مسئول پیگیری", "اطلاعات غیرمرتبط همکاران"], correct: 1 }], passScore: 70 },
    ];
    await tx.insert(courses).values(courseRows);
    for (const [i, e] of selectedStaff.entries()) await tx.insert(enrollments).values(courseRows.map((c, j) => ({ employeeId: e.id, courseId: c.id, dueDate: shiftDate(5 + j * 4), completedLessons: i > 2 && j === 0 ? c.lessons.map(l => l.id) : [], status: i > 2 && j === 0 ? "completed" : "assigned", score: i > 2 && j === 0 ? 100 : null, completedAt: i > 2 && j === 0 ? new Date() : null })));
    const questions = [{ id: "leadership", text: "مدیر من انتظارات شغلی را روشن بیان می‌کند.", type: "scale" as const, dimension: "رهبری" }, { id: "balance", text: "برنامه شیفت‌ها با تعادل کار و زندگی من سازگار است.", type: "scale" as const, dimension: "تعادل کار و زندگی" }, { id: "growth", text: "فرصت یادگیری و رشد در آبان دارم.", type: "scale" as const, dimension: "رشد و یادگیری" }, { id: "enps", text: "چقدر آبان را به عنوان محل کار به دوستانتان پیشنهاد می‌کنید؟", type: "enps" as const, dimension: "توصیه همکاری" }];
    const surveyRows = [{ id: randomUUID(), title: "حالِ تیم آبان؛ یک گفت‌وگوی کوتاه", description: "کمتر از دو دقیقه برای بهتر شدن تجربه همکاری. پاسخ‌ها بدون نام و تنها به‌صورت تجمیعی گزارش می‌شوند.", department: "all", deadline: shiftDate(12), status: "active", questions }, { id: randomUUID(), title: "تجربه همکاری؛ دوره قبل", description: "نظرسنجی نمونه تکمیل‌شده برای نمایش تحلیل و اقدام اصلاحی.", department: "all", deadline: shiftDate(-3), status: "closed", questions }];
    await tx.insert(surveys).values(surveyRows);
    const active = staff.filter(e => ["active", "on_leave"].includes(e.status));
    for (const [index, survey] of surveyRows.entries()) { for (let i = 0; i < active.length; i += 200) await tx.insert(surveyAudience).values(active.slice(i, i + 200).map((e, n) => ({ surveyId: survey.id, employeeId: e.id, department: e.department, participated: e.id !== sara.id && (index ? (i + n) < 240 : (i + n) < 54) }))); const responders = active.filter(e => e.id !== sara.id).slice(0, index ? 239 : 53); await tx.insert(surveyResponses).values(responders.map((e, i) => ({ surveyId: survey.id, department: e.department, answers: { leadership: 3 + i % 3, balance: 2 + i % 4, growth: 3 + i % 3, enps: 6 + i % 5 } }))); }
    await tx.insert(improvements).values({ surveyId: surveyRows[1].id, title: "بازنگری برنامه شیفت‌ها با مشارکت همکاران", employeeId: manager.id, dueDate: shiftDate(8), status: "in_progress", notes: "بر اساس امتیاز تعادل کار و زندگی؛ برگزاری یک جلسه با نمایندگان شیفت‌ها." });
    await tx.insert(salaryPolicies).values(departments.map((department, i) => ({ department, minimum: 19000000 + i * 1000000, midpoint: 26000000 + i * 1000000, maximum: 36000000 + i * 2000000, increasePercent: 20, complexityPercent: i === 0 ? 110 : 100, strategy: i === 0 ? "competitive" : "market", source: "بازه داخلی نمونه آبان؛ فاقد اتصال به داده بازار" })));
    await tx.insert(talentEvents).values([{ module: "recruitment", title: "فرصت‌های همکاری فصل جدید منتشر شدند", actorName: "منابع انسانی آبان" }, { module: "learning", title: "مسیر آشنایی با فرهنگ آبان در دسترس همکاران قرار گرفت", actorName: "واحد آموزش", employeeId: sara.id }, { module: "onboarding", title: "برنامه خوش‌آمدگویی شما آماده است", actorName: "منابع انسانی آبان", employeeId: sara.id }]);
    await tx.insert(talentVersions).values({ key: "talent-v1" });
  });
}
