"use client";
import { useRef, useState, type FormEvent } from "react";
import { ArrowLeft, Award, BookOpen, CalendarDays, Check, CheckCircle2, ChevronLeft, Clock3, Download, ExternalLink, FileText, GraduationCap, HeartPulse, Info, LoaderCircle, Mail, MessageCircle, Pencil, Phone, Plus, Printer, ShieldCheck, Sparkles, Star, Trash2, Upload, Users, Wallet } from "lucide-react";
import { useWorkspace } from "@/components/workspace-context";
import { Avatar, EmptyState, Field, Modal, Pagination, RelativeTime, SubmitButton } from "@/components/ui";
import { apiRequest, connectionError } from "@/lib/api-client";
import { dateFa, fa, money, todayISO } from "@/lib/types";
import { percentComplete, stages, taskRoleLabels, type Applicant, type OnboardingPlan, type Course, type Survey, type SalaryScenario } from "@/lib/talent-types";
import { useTalent } from "./context";
import { EntityActions, Progress, SectionHead, StateTag, TalentTabs } from "./shared";

export function TalentDetails() {
  const { dialog, close } = useTalent(); if (!dialog) return null;
  const { kind, item } = dialog;
  if (kind === "applicant-detail") return <Modal title="پرونده متقاضی" subtitle="شناخت بهتر، تصمیم منصفانه‌تر" onClose={close} wide><ApplicantDetail initial={item as unknown as Applicant} /></Modal>;
  if (kind === "plan-detail") return <Modal title="مسیر ورود همکار" subtitle="هر قدم، یک شروع مطمئن‌تر" onClose={close} wide><PlanDetail initial={item as unknown as OnboardingPlan} /></Modal>;
  if (kind === "course-player") return <Modal title="مسیر یادگیری" subtitle="آکادمی داخلی آبان" onClose={close} wide><CoursePlayer initial={item as unknown as Course} /></Modal>;
  if (kind === "survey-response") return <Modal title="صدای شما شنیده می‌شود" subtitle="پاسخ‌ها فقط به‌صورت تجمیعی و بدون نام گزارش خواهند شد." onClose={close} wide><SurveyResponse survey={item as unknown as Survey} /></Modal>;
  if (kind === "survey-report") return <Modal title="گزارش نبض سازمان" subtitle="بینش قابل اقدام، با حفظ محرمانگی" onClose={close} wide><SurveyReport survey={item as unknown as Survey} /></Modal>;
  if (kind === "scenario-detail") return <Modal title="بررسی سناریوی حقوق" subtitle="مقایسه شفاف پیش از تأیید نهایی" onClose={close} wide><ScenarioDetail initial={item as unknown as SalaryScenario} /></Modal>;
  return null;
}
function ApplicantDetail({ initial }: { initial: Applicant }) {
  const { data, open, mutate, busy, reload, close } = useTalent(); const { data: workspace, notify } = useWorkspace(); const [tab, setTab] = useState("profile"); const [uploading, setUploading] = useState(false); const fileInput = useRef<HTMLInputElement>(null); const candidate = data.applicants.find(c => c.id === initial.id) || initial; const job = data.jobs.find(j => j.id === candidate.jobId); const files = data.files.filter(f => f.applicantId === candidate.id); const notes = data.notes.filter(n => n.applicantId === candidate.id);
  async function upload(file?: File) { if (!file) return; setUploading(true); try { const form = new FormData(); form.append("file", file); form.append("applicantId", candidate.id); await apiRequest("/api/talent/files", { method: "POST", body: form }); await reload(); notify("رزومه با موفقیت ذخیره شد."); } catch (e) { notify(connectionError(e).message, true); } finally { setUploading(false); if (fileInput.current) fileInput.current.value = ""; } }
  async function removeFile(id: string) { if (!window.confirm("پیوست انتخاب‌شده حذف شود؟")) return; setUploading(true); try { await apiRequest(`/api/talent/files?id=${id}`, { method: "DELETE" }); await reload(); notify("پیوست حذف شد."); } catch (e) { notify(connectionError(e).message, true); } finally { setUploading(false); } }
  return <><div className="modal-body tl-detail"><div className="tl-profile-header"><Avatar name={candidate.name} size="large" /><div><h2>{candidate.name}</h2><p>{job?.title} · {job?.department}</p><div className="tl-stars">{Array.from({ length: 5 }, (_, i) => <Star size={14} key={i} fill={i < candidate.rating ? "#dabb75" : "none"} />)}<span>{fa(candidate.rating)} از ۵</span></div></div><span className="badge blue">{stages.find(s => s.id === candidate.stage)?.label}</span></div><TalentTabs active={tab} onChange={setTab} tabs={[{ id: "profile", label: "اطلاعات و سوابق" }, { id: "files", label: "رزومه و فایل‌ها", count: files.length }, { id: "notes", label: "یادداشت و تاریخچه", count: notes.length }, { id: "interviews", label: "مصاحبه‌ها" }]} />
    {tab === "profile" && <><div className="tl-profile-facts"><span><Mail size={15} /><b dir="ltr">{candidate.email}</b></span><span><Phone size={15} /><b dir="ltr">{candidate.phone || "ثبت نشده"}</b></span><span><Clock3 size={15} /><b>{fa(candidate.experience)} سال سابقه مرتبط</b></span><span><Wallet size={15} /><b>{candidate.expectedSalary ? money(candidate.expectedSalary) : "حقوق توافقی"}</b></span></div><div className="tl-detail-section"><h3>مهارت‌ها و سوابق</h3><p>{candidate.skills || "مهارتی ثبت نشده است."}</p><p>{candidate.summary || "خلاصه رزومه‌ای ثبت نشده است."}</p><div className="tl-candidate-tags">{candidate.tags.map(t => <span key={t}>{t}</span>)}</div></div><div className="tl-detail-section"><h3>اطلاعات جذب</h3><div className="tl-profile-facts"><span>منبع رزومه <b>{candidate.source}</b></span><span>تاریخ دریافت <b>{dateFa(candidate.createdAt)}</b></span></div></div>{candidate.stage !== "hired" && <Field label="مرحله فعلی در فرایند جذب"><select aria-label="تغییر مرحله متقاضی" value={candidate.stage} disabled={busy} onChange={e => mutate("applicant.move", { id: candidate.id, fromStage: candidate.stage, stage: e.target.value })}>{stages.filter(s => s.id !== "hired").map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select></Field>}</>}
    {tab === "files" && <><div className="tl-detail-section"><SectionHead title="فایل‌های متقاضی" subtitle="PDF تا ۲ مگابایت؛ حداکثر ۵ پیوست"><button className="btn small primary" disabled={uploading} onClick={() => fileInput.current?.click()}>{uploading ? <LoaderCircle size={15} className="spin" /> : <Upload size={15} />}بارگذاری رزومه</button><input type="file" accept=".pdf" ref={fileInput} hidden onChange={e => upload(e.target.files?.[0])} /></SectionHead>{files.length ? <div className="tl-file-list">{files.map(f => <div key={f.id}><span className="tl-module-icon blue"><FileText size={21} /></span><span><strong>{f.name}</strong><small>{fa(Math.round(f.size / 1024))} کیلوبایت · PDF</small></span><a className="icon-button" href={`/api/talent/files?id=${f.id}`} aria-label={`دانلود ${f.name}`}><Download size={17} /></a><button className="icon-button danger-hover" disabled={uploading} onClick={() => removeFile(f.id)} aria-label="حذف پیوست"><Trash2 size={16} /></button></div>)}</div> : <EmptyState title="هنوز پیوستی ثبت نشده" description="رزومه متقاضی را به این پرونده اضافه کنید." />}</div><p className="tl-page-note">فایل‌ها فقط پس از احراز هویت دریافت می‌شوند. پیوست‌های ناشناس را با نرم‌افزار به‌روز باز کنید؛ اسکن بدافزار به این نسخه متصل نیست.</p></>}
    {tab === "notes" && <div className="tl-detail-section"><SectionHead title="گفت‌وگوی تیم جذب"><button className="btn small primary" onClick={() => open("note", { id: candidate.id })}><Plus size={14} />یادداشت / ارزیابی</button></SectionHead><div className="tl-timeline">{notes.map(n => <div key={n.id}><i /><div><div><strong>{n.actorName}</strong><small><RelativeTime date={n.createdAt} /></small></div><p>{n.body}</p>{n.kind === "evaluation" && <span className="badge amber"><Star size={12} />امتیاز {fa(n.score)} از ۵</span>}</div></div>)}</div></div>}
    {tab === "interviews" && <div className="tl-detail-section"><SectionHead title="جلسه‌های آشنایی"><button className="btn small primary" onClick={() => open("interview", undefined, { applicantId: candidate.id })}><Plus size={14} />ثبت مصاحبه</button></SectionHead>{data.interviews.filter(i => i.applicantId === candidate.id).map(i => <div className="tl-interview-mini" key={i.id}><CalendarDays size={21} /><div><strong>{dateFa(i.startsAt)} · {new Intl.DateTimeFormat("fa-IR", { hour: "2-digit", minute: "2-digit" }).format(new Date(i.startsAt))}</strong><p>{i.mode} · {i.location}</p><small>{workspace.employees.find(e => e.id === i.interviewerId)?.name}{i.feedback && ` — ${i.feedback}`}</small></div><StateTag status={i.status} /><EntityActions kind="interview" item={i} /></div>)}</div>}
  </div><div className="modal-footer"><div className="row-actions"><button className="btn secondary" onClick={close}>بستن</button>{candidate.stage !== "hired" && <button className="btn secondary" onClick={() => open("applicant", candidate)}><Pencil size={15} />ویرایش پرونده</button>}{candidate.stage !== "hired" && <button className="icon-button danger-hover" aria-label="حذف متقاضی" onClick={() => open("confirm", { action: "applicant.delete", id: candidate.id, title: "حذف متقاضی", description: "پرونده، پیوست‌ها و تاریخچه این متقاضی حذف شود؟" })}><Trash2 size={16} /></button>}</div>{candidate.stage === "offer" && workspace.user.role === "admin" && <button className="btn primary" onClick={() => open("hire", candidate)}><Users size={16} />تأیید استخدام</button>}</div></>;
}
function PlanDetail({ initial }: { initial: OnboardingPlan }) {
  const { data, open, mutate, busy, close } = useTalent(); const { data: workspace } = useWorkspace(); const plan = data.plans.find(p => p.id === initial.id) || initial; const e = workspace.employees.find(e => e.id === plan.employeeId); const tasks = data.tasks.filter(t => t.planId === plan.id); const done = tasks.filter(t => t.done).length; const admin = workspace.user.role === "admin", manager = workspace.user.role === "manager";
  return <><div className="modal-body tl-detail"><div className="tl-plan-welcome"><Avatar employee={e} size="large" /><div><h2>{e?.name}، به آبان خوش آمدید 🌊</h2><p>{plan.title} · شروع {dateFa(plan.startDate)}</p></div></div><p className="tl-welcome-text">{plan.welcome}</p><div className="tl-detail-section"><SectionHead title="قدم‌به‌قدم کنار شما" subtitle={`${fa(done)} از ${fa(tasks.length)} وظیفه تکمیل شده است`}>{(admin || manager) && <button className="btn small secondary" onClick={() => open("task", undefined, { planId: plan.id })}><Plus size={14} />وظیفه جدید</button>}</SectionHead><Progress value={percentComplete(done, tasks.length)} /><div className="tl-checklist">{tasks.map(t => { const allowed = admin || manager && t.ownerRole === "manager" || workspace.user.employeeId === plan.employeeId && t.ownerRole === "employee"; const overdue = !t.done && t.dueDate < todayISO(); return <div key={t.id} className={t.done ? "completed" : ""}><button role="checkbox" aria-checked={t.done} aria-label={`تکمیل ${t.title}`} className="tl-task-checkbox" disabled={!allowed || busy} onClick={() => mutate("task.toggle", { id: t.id, done: !t.done })}>{t.done && <Check size={16} />}</button><div><strong>{t.title}</strong><small>{taskRoleLabels[t.ownerRole]} · {dateFa(t.dueDate)}{t.done && ` · ${t.completedBy}`}</small></div>{overdue && <span className="badge amber">نیاز به پیگیری</span>}{(admin || manager) && <EntityActions kind="task" item={t} deleteAction="task.delete" />}</div>; })}</div></div><div className="inline-info"><ShieldCheck size={16} />هر وظیفه فقط توسط مسئول مربوط یا مدیر سیستم تکمیل می‌شود.</div></div><div className="modal-footer"><button className="btn secondary" onClick={close}>بستن برنامه</button>{(admin || manager) && <button className="btn primary" onClick={() => open("plan-edit", plan)}><Pencil size={15} />شخصی‌سازی راهنما</button>}</div></>;
}
function CoursePlayer({ initial }: { initial: Course }) {
  const { data, mutate, busy, close } = useTalent(); const { data: workspace, notify } = useWorkspace(); const course = data.courses.find(c => c.id === initial.id) || initial; const enrollment = data.enrollments.find(e => e.courseId === course.id && e.employeeId === workspace.user.employeeId); const [index, setIndex] = useState(0); const [quizMode, setQuizMode] = useState(false); const [answers, setAnswers] = useState<Record<string, number>>({}); const lesson = course.lessons[index];
  async function enroll() { await mutate("enrollment.assign", { courseId: course.id, dueDate: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10) }, "مسیر یادگیری شما آغاز شد."); }
  async function mark() { if (!enrollment || !lesson) return; const result = await mutate("enrollment.lesson", { id: enrollment.id, lessonId: lesson.id }, "پیشرفت شما ثبت شد."); if (result) { if (index < course.lessons.length - 1) setIndex(i => i + 1); else setQuizMode(true); } }
  async function submit(e: FormEvent) { e.preventDefault(); if (!enrollment) return; const result = await mutate("enrollment.quiz", { id: enrollment.id, answers }, "آزمون شما در سرور ارزیابی شد."); if (result) notify(result.passed ? `تبریک! نمره شما ${fa(Number(result.score))} از ۱۰۰ است.` : `نمره شما ${fa(Number(result.score))} است. درس‌ها را مرور و دوباره تلاش کنید.`, !result.passed); }
  if (enrollment?.status === "completed") return <><div className="modal-body"><div className="tl-certificate print-document"><span className="tl-certificate-icon"><Award size={54} strokeWidth={1.3} /></span><span className="eyebrow">آکادمی داخلی پارک آبی آبان</span><h2>گواهی تکمیل مسیر یادگیری</h2><p>همکار گرامی <strong>{workspace.user.name}</strong></p><p>دوره «{course.title}» را با موفقیت به پایان رسانده است.</p><div className="tl-certificate-score">{fa(enrollment.score || 0)}<small>از ۱۰۰ امتیاز</small></div><div><span>{dateFa(enrollment.completedAt || new Date().toISOString())}</span><span>شناسه: {enrollment.id.slice(0, 8).toUpperCase()}</span></div><small>گواهی داخلی مجموعه؛ فاقد اعتبار حرفه‌ای یا مجوز فعالیت تخصصی.</small></div></div><div className="modal-footer"><button className="btn secondary" onClick={close}>بستن</button><button className="btn primary" onClick={() => window.print()}><Printer size={16} />چاپ کارنامه</button></div></>;
  return <><div className="modal-body tl-detail"><div className="tl-course-heading"><span className="tl-module-icon teal"><GraduationCap size={29} /></span><div><h2>{course.title}</h2><p>{course.instructor} · {fa(course.lessons.length)} درس · حدنصاب {fa(course.passScore)}٪</p></div></div>{enrollment && <Progress value={percentComplete(enrollment.completedLessons.length, course.lessons.length)} />}
    <div className="tl-player"><aside>{course.lessons.map((l, i) => <button key={l.id} className={!quizMode && index === i ? "active" : ""} onClick={() => { setIndex(i); setQuizMode(false); }}>{enrollment?.completedLessons.includes(l.id) ? <CheckCircle2 size={16} /> : <span>{fa(i + 1)}</span>}<strong>{l.title}</strong></button>)}<button className={quizMode ? "active" : ""} onClick={() => setQuizMode(true)}><GraduationCap size={16} /><strong>آزمون پایان دوره</strong></button></aside><section>{!quizMode ? <><span className="eyebrow">درس {fa(index + 1)} · {fa(lesson?.minutes || 0)} دقیقه مطالعه</span><h3>{lesson?.title}</h3><p className="tl-lesson-content">{lesson?.content}</p>{lesson?.url && <a className="btn secondary small" href={lesson.url} target="_blank" rel="noopener noreferrer"><ExternalLink size={14} />محتوای تکمیلی</a>}{enrollment ? <button className="btn primary" disabled={busy} onClick={mark}><Check size={15} />مطالعه کردم؛ ادامه مسیر</button> : workspace.user.employeeId ? <button className="btn primary" disabled={busy || course.status !== "published"} onClick={enroll}>شروع یادگیری<ArrowLeft size={15} /></button> : <div className="inline-info"><Info size={16} />پیش‌نمایش مدیر؛ تخصیص دوره از کتابخانه انجام می‌شود.</div>}</> : !enrollment || course.lessons.some(l => !enrollment.completedLessons.includes(l.id)) ? <EmptyState title="ابتدا مسیر یادگیری را طی کنید" description="پس از ثبت مطالعه همه درس‌ها، آزمون در دسترس شما قرار می‌گیرد." icon={BookOpen} /> : <form onSubmit={submit}><h3>آنچه یاد گرفتیم</h3><p className="tl-page-note">پاسخ همه سؤال‌ها را انتخاب کنید. ارزیابی در سرور انجام می‌شود.</p>{course.quiz.map((q, i) => <fieldset className="tl-quiz-question" key={q.id}><legend>{fa(i + 1)}. {q.text}</legend>{q.options.map((option, index) => <label key={index}><input required type="radio" name={q.id} checked={answers[q.id] === index} onChange={() => setAnswers(a => ({ ...a, [q.id]: index }))} /><span>{option}</span></label>)}</fieldset>)}<SubmitButton busy={busy}>ثبت و ارزیابی آزمون<Check size={16} /></SubmitButton>{enrollment.score !== null && <p className="inline-info">نمره آخرین تلاش: {fa(enrollment.score)} از ۱۰۰</p>}</form>}</section></div></div><div className="modal-footer"><button className="btn secondary" onClick={close}>بستن مسیر یادگیری</button><span className="tl-page-note">پیشرفت شما ذخیره می‌شود.</span></div></>;
}
function SurveyResponse({ survey }: { survey: Survey }) {
  const { mutate, busy, close } = useTalent(); const [answers, setAnswers] = useState<Record<string, number>>({});
  async function submit(e: FormEvent) { e.preventDefault(); if (await mutate("survey.respond", { id: survey.id, answers }, "از همراهی شما ممنونیم؛ پاسخ بی‌نام شما ثبت شد.")) close(); }
  return <form onSubmit={submit}><div className="modal-body tl-detail"><div className="tl-survey-intro"><HeartPulse size={34} /><h2>{survey.title}</h2><p>{survey.description}</p></div>{survey.questions.map((q, i) => <fieldset key={q.id} className="tl-rating-question"><legend><span>{fa(i + 1)}</span>{q.text}</legend><div className={`tl-rating-scale ${q.type === "enps" ? "enps" : ""}`}>{Array.from({ length: q.type === "enps" ? 11 : 5 }, (_, index) => q.type === "enps" ? index : index + 1).map(n => <label key={n} className={answers[q.id] === n ? "selected" : ""}><input required type="radio" name={q.id} value={n} checked={answers[q.id] === n} onChange={() => setAnswers(a => ({ ...a, [q.id]: n }))} /><span>{fa(n)}</span></label>)}</div><div className="tl-rating-labels"><span>{q.type === "enps" ? "اصلاً توصیه نمی‌کنم" : "کاملاً مخالفم"}</span><span>{q.type === "enps" ? "حتماً توصیه می‌کنم" : "کاملاً موافقم"}</span></div></fieldset>)}<div className="inline-info"><ShieldCheck size={17} />برای جلوگیری از پاسخ تکراری فقط وضعیت مشارکت ثبت می‌شود؛ محتوای پاسخ به شناسه کارمند متصل نیست و نتایج فردی در پنل نمایش داده نمی‌شود.</div></div><div className="modal-footer"><button className="btn secondary" type="button" onClick={close}>بعداً پاسخ می‌دهم</button><SubmitButton busy={busy}>ثبت نهایی پاسخ‌ها<Check size={16} /></SubmitButton></div></form>;
}
function SurveyReport({ survey }: { survey: Survey }) {
  const { data, open, close } = useTalent(); const m = data.metrics.find(m => m.surveyId === survey.id)!; if (!m.reportReady) return <><EmptyState title="هنوز شرایط انتشار گزارش فراهم نیست" description={`گزارش پس از پایان نظرسنجی و دریافت حداقل ۵ پاسخ نمایش داده می‌شود. تعداد پاسخ فعلی: ${fa(m.responses)}`} icon={ShieldCheck} /><div className="modal-footer"><button className="btn secondary" onClick={close}>بستن</button></div></>;
  const lowest = [...m.dimensions].filter(d => d.type === "scale").sort((a, b) => a.percent - b.percent)[0];
  return <><div className="modal-body tl-detail"><div className="tl-survey-intro"><HeartPulse size={32} /><h2>{survey.title}</h2><p>{fa(m.responses)} پاسخ از {fa(m.audience)} همکار · گزارش تجمیعی بدون نام</p></div><div className="tl-report-kpis"><div><span>امتیاز تجربه همکاری</span><strong>{m.score === null ? "—" : fa(m.score)}<small>/ ۱۰۰</small></strong></div><div><span>شاخص توصیه همکاری eNPS</span><strong dir="ltr">{m.enps === null ? "—" : fa(m.enps)}<small>از ۱۰۰− تا ۱۰۰+</small></strong></div><div><span>مشارکت در نظرسنجی</span><strong>{fa(percentComplete(m.responses, m.audience))}<small>درصد</small></strong></div></div><SectionHead title="شاخص‌های تجربه کارکنان" subtitle="مقیاس رضایت ۱ تا ۵ به صفر تا صد تبدیل شده است." /><div className="tl-dimension-bars">{m.dimensions.filter(d => d.type === "scale").map(d => <div key={d.id}><span>{d.title}</span><Progress value={d.percent} /><strong>{fa(d.average)} / ۵</strong></div>)}</div><SectionHead title="نقشه وضعیت واحدها" subtitle="گروه‌های کمتر از ۵ پاسخ برای حفظ محرمانگی نمایش داده نمی‌شوند." /><div className="tl-heatmap">{m.departments.map(d => <div className={d.score === null ? "hidden-score" : d.score < 55 ? "low-score" : "good-score"} key={d.department}><span>{d.department}</span><strong>{d.score === null ? <ShieldCheck size={22} /> : fa(d.score)}</strong><small>{d.score === null ? "مشارکت کمتر از حد انتشار" : `${fa(d.count)} پاسخ · از ۱۰۰`}</small></div>)}</div>{lowest && <div className="tl-recommendation"><Sparkles size={23} /><div><h3>فرصت بهبود: {lowest.title}</h3><p>برای شناخت بهتر تجربه این حوزه، گفت‌وگوی تیمی برگزار کنید و یک اقدام مشخص با مسئول و زمان‌بندی تعریف کنید. این پیشنهاد قاعده‌محور است، نه تحلیل هوش مصنوعی.</p><button className="text-button" onClick={() => open("improvement", undefined, { surveyId: survey.id, title: `بهبود ${lowest.title} با مشارکت تیم` })}>تبدیل به اقدام اصلاحی<ArrowLeft size={14} /></button></div></div>}<p className="tl-page-note">eNPS = درصد امتیازهای ۹ و ۱۰، منهای درصد امتیازهای صفر تا ۶؛ امتیازهای ۷ و ۸ خنثی‌اند.</p></div><div className="modal-footer"><button className="btn secondary" onClick={close}>بستن گزارش</button><a className="btn primary" href="/api/talent/export?type=pulse"><Download size={16} />خروجی گزارش تجمیعی</a></div></>;
}
function ScenarioDetail({ initial }: { initial: SalaryScenario }) {
  const { data, open, close } = useTalent(); const { data: workspace } = useWorkspace(); const scenario = data.scenarios.find(s => s.id === initial.id) || initial; const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const current = scenario.entries.reduce((n, e) => n + e.current, 0); const proposed = scenario.entries.reduce((n, e) => n + e.proposed, 0); const rows = scenario.entries.filter(e => `${e.name} ${e.code} ${e.department}`.includes(query));
  return <><div className="modal-body tl-detail"><SectionHead title={scenario.title} subtitle={`محاسبه توسط ${scenario.createdBy} در ${dateFa(scenario.createdAt)}`}><StateTag status={scenario.status} /></SectionHead><div className="tl-report-kpis salary"><div><span>بودجه مبنا</span><strong>{fa(Math.round(current / 1000000))}<small>میلیون تومان</small></strong></div><div><span>بودجه پیشنهادی</span><strong>{fa(Math.round(proposed / 1000000))}<small>میلیون تومان</small></strong></div><div><span>اثر بر بودجه ماهانه</span><strong>+{fa(Math.round((proposed - current) / Math.max(1, current) * 100))}<small>درصد</small></strong></div></div><Field label="جستجوی همکار در سناریو"><input value={query} onChange={e => { setQuery(e.target.value); setPage(1); }} placeholder="نام، کد پرسنلی یا واحد..." /></Field><div className="table-scroll tl-compare-table"><table className="data-table"><thead><tr><th>همکار</th><th>حقوق مبنا</th><th>پیشنهاد</th><th>افزایش</th></tr></thead><tbody>{rows.slice((page - 1) * 10, page * 10).map(e => <tr key={e.employeeId}><td><strong>{e.name}</strong><small className="tl-cell-sub">{e.department}</small></td><td>{fa(e.current)}</td><td className="net-pay">{fa(e.proposed)}</td><td>+{fa(e.proposed - e.current)}</td></tr>)}</tbody></table></div><Pagination page={page} count={rows.length} onChange={setPage} /><div className="inline-info"><ShieldCheck size={17} />مبالغ تومان است. تأیید نهایی فقط توسط مدیر سیستم انجام می‌شود. تغییر حقوق یا وضعیت کارمند پس از محاسبه، از اعمال سناریوی قدیمی جلوگیری می‌کند.</div></div><div className="modal-footer"><a className="btn secondary" href={`/api/talent/export?type=compensation&id=${scenario.id}`}><Download size={15} />دریافت اکسل</a>{scenario.status === "draft" && workspace.user.role === "admin" ? <button className="btn primary" onClick={() => open("confirm", { action: "salary.apply", id: scenario.id, title: "اعمال سناریوی حقوق پایه", description: `حقوق پایه ${fa(scenario.entries.length)} همکار با بودجه ماهانه ${money(proposed)} به‌روزرسانی می‌شود. فیش‌های حقوقی قبلی تغییر نمی‌کنند. این تصمیم مدیریتی تأیید می‌شود؟` })}><Check size={16} />تأیید و اعمال حقوق پایه</button> : <button className="btn secondary" onClick={close}>بستن</button>}</div></>;
}
