"use client";
import { useState, type FormEvent } from "react";
import { Check, Plus, Trash2, Info, ShieldCheck } from "lucide-react";
import { useWorkspace } from "@/components/workspace-context";
import { Field, Modal, SubmitButton } from "@/components/ui";
import { JalaliDatePicker, JalaliDateTimePicker } from "@/components/calendar";
import { departments, todayISO, fa } from "@/lib/types";
import { taskRoleLabels, strategyLabels, sourceLabels, type TaskSpec, type Lesson, type QuizQuestion, type SurveyQuestion } from "@/lib/talent-types";
import { useTalent } from "./context";

type Values = Record<string, unknown>;
type FormField = { key: string; label: string; type?: string; options?: { value: string; label: string }[]; required?: boolean; min?: number; max?: number; hint?: string; wide?: boolean };
const options = (values: string[] | Record<string, string>) => Array.isArray(values) ? values.map(v => ({ value: v, label: v })) : Object.entries(values).map(([value, label]) => ({ value, label }));
const inDays = (n: number) => new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);
const supported = ["job", "applicant", "note", "interview", "hire", "template", "plan", "plan-edit", "task", "course", "assign", "survey", "improvement", "policy", "simulate", "rename", "confirm"];
export function TalentForms() { const { dialog } = useTalent(); if (!dialog || !supported.includes(dialog.kind)) return null; return <TalentForm key={`${dialog.kind}-${dialog.item?.id || "new"}`} />; }
function TalentForm() {
  const { dialog, close, mutate, busy, data } = useTalent(); const { data: workspace } = useWorkspace(); const kind = dialog!.kind, item = dialog!.item || {}, extra = dialog!.extra || {};
  const admin = workspace.user.role === "admin"; const me = workspace.employees.find(e => e.id === workspace.user.employeeId); const staff = workspace.employees.filter(e => ["active", "on_leave"].includes(e.status));
  const staffOptions = staff.map(e => ({ value: e.id, label: `${e.name} · ${fa(e.code)}` })); const departmentOptions = options(admin || workspace.user.role === "finance" ? departments : [me?.department || departments[0]]);
  const defaults: Record<string, Values> = {
    job: { department: me?.department || departments[0], title: "", location: "تهران · پارک آبی آبان", contract: "تمام‌وقت", description: "", requirements: "", status: "draft", openings: 1, salaryMin: 18000000, salaryMax: 30000000, hiringCost: 0, deadline: inDays(30) },
    applicant: { jobId: extra.jobId || data.jobs[0]?.id || "", name: "", email: "", phone: "", source: sourceLabels[0], tags: "", skills: "", experience: 0, expectedSalary: 0, summary: "" },
    note: { kind: "note", score: 4, body: "" },
    interview: { applicantId: extra.applicantId || data.applicants[0]?.id || "", interviewerId: me?.id || staff[0]?.id || "", startsAt: `${inDays(1)}T10:00`, duration: 45, mode: "حضوری", location: "اتاق جلسات منابع انسانی", status: "scheduled", feedback: "", score: 0 },
    hire: { code: String(Math.max(1000, ...workspace.employees.map(e => Number(e.code) || 0)) + 1), baseSalary: Number(item.expectedSalary) || 20000000, hireDate: todayISO(), password: "", templateId: "" },
    template: { title: "", department: "all", welcome: "به تیم آبان خوش آمدید. مسیر روزهای اول همکاری شما در این برنامه مشخص شده است.", tasks: [{ title: "آشنایی با تیم و همیار", ownerRole: "manager", offsetDays: 0 }, { title: "مطالعه راهنمای همکاری", ownerRole: "employee", offsetDays: 1 }] },
    plan: { employeeId: staff[0]?.id || "", templateId: data.templates[0]?.id || "", startDate: todayISO() },
    task: { planId: extra.planId || "", title: "", ownerRole: "employee", dueDate: inDays(3) },
    course: { title: "", category: "مهارت‌های عمومی", instructor: "تیم آموزش آبان", description: "", level: "مقدماتی", status: "draft", passScore: 70, lessons: [{ id: crypto.randomUUID(), title: "", content: "", minutes: 15, url: "" }], quiz: [{ id: crypto.randomUUID(), text: "", options: ["", "", ""], correct: 0 }] },
    assign: { courseId: extra.courseId || data.courses.find(c => c.status === "published")?.id || "", employeeId: staff[0]?.id || "", target: "single", department: "all", dueDate: inDays(14) },
    survey: { title: "", description: "پاسخ‌های شما فقط به‌صورت تجمیعی و بدون نام گزارش می‌شود.", department: "all", deadline: inDays(14), questions: [{ id: crypto.randomUUID(), text: "از تجربه همکاری در آبان رضایت دارم.", type: "scale", dimension: "رضایت کلی" }, { id: crypto.randomUUID(), text: "چقدر آبان را به عنوان محل کار توصیه می‌کنید؟", type: "enps", dimension: "توصیه همکاری" }] },
    improvement: { surveyId: extra.surveyId || data.surveys[0]?.id || "", title: "", employeeId: me?.id || staff[0]?.id || "", dueDate: inDays(14), status: "open", notes: "" },
    policy: { department: departments[0], minimum: 18000000, midpoint: 26000000, maximum: 36000000, increasePercent: 20, complexityPercent: 100, strategy: "market", source: "مصوبه و بازه داخلی مجموعه" },
    simulate: { title: `پیشنهاد بازنگری حقوق ${new Intl.DateTimeFormat("fa-IR", { year: "numeric" }).format(new Date())}`, department: "all" },
  };
  const [values, setValues] = useState<Values>(() => ({ ...defaults[kind], ...item, ...extra, ...(kind === "applicant" && Array.isArray(item.tags) ? { tags: item.tags.join("، ") } : {}), ...(kind === "interview" && item.startsAt ? { startsAt: new Date(Date.parse(String(item.startsAt)) - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16) } : {}) }));
  const set = (key: string, value: unknown) => setValues(old => ({ ...old, [key]: value }));
  const get = (key: string) => String(values[key] ?? "");
  const configs: Record<string, { title: string; action: string; fields: FormField[] }> = {
    job: { title: item.id ? "ویرایش فرصت شغلی" : "یک فرصت تازه برای همکاری", action: "job.save", fields: [{ key: "title", label: "عنوان شغلی" }, { key: "department", label: "واحد سازمانی", options: departmentOptions }, { key: "location", label: "محل کار" }, { key: "contract", label: "نوع همکاری", options: options(["تمام‌وقت", "پاره‌وقت", "شیفتی", "قراردادی"]) }, { key: "openings", label: "ظرفیت استخدام", type: "number", min: 1, max: 1000 }, { key: "deadline", label: "آخرین مهلت دریافت درخواست", type: "date" }, { key: "salaryMin", label: "حداقل حقوق (تومان)", type: "number", min: 0 }, { key: "salaryMax", label: "حداکثر حقوق (تومان)", type: "number", min: 0 }, { key: "hiringCost", label: "هزینه جذب ثبت‌شده (تومان)", type: "number", min: 0, hint: "برای گزارش هزینه به ازای استخدام" }, { key: "status", label: "وضعیت انتشار", options: options({ draft: "پیش‌نویس", open: "انتشار در صفحه همکاری", closed: "بسته" }) }, { key: "description", label: "شرح شغل و مسئولیت‌ها", type: "textarea", wide: true }, { key: "requirements", label: "شرایط احراز و مهارت‌ها", type: "textarea", wide: true, required: false }] },
    applicant: { title: item.id ? "ویرایش پرونده متقاضی" : "افزودن به بانک رزومه", action: "applicant.save", fields: [{ key: "name", label: "نام و نام خانوادگی" }, { key: "jobId", label: "فرصت شغلی", options: data.jobs.map(j => ({ value: j.id, label: j.title })) }, { key: "email", label: "ایمیل", type: "email" }, { key: "phone", label: "شماره تماس", type: "tel", required: false }, { key: "source", label: "منبع دریافت رزومه", options: options(sourceLabels) }, { key: "experience", label: "سابقه مرتبط (سال)", type: "number", min: 0, max: 50 }, { key: "expectedSalary", label: "حقوق درخواستی (تومان)", type: "number", min: 0 }, { key: "tags", label: "برچسب‌ها", hint: "با ویرگول جدا کنید؛ حداکثر ۸ برچسب", required: false }, { key: "skills", label: "مهارت‌ها", required: false, wide: true }, { key: "summary", label: "خلاصه سوابق", type: "textarea", required: false, wide: true }] },
    note: { title: "یادداشت و ارزیابی تیم جذب", action: "applicant.note", fields: [{ key: "kind", label: "نوع ثبت", options: options({ note: "یادداشت داخلی", evaluation: "ارزیابی امتیازی" }) }, { key: "score", label: "امتیاز از ۵", type: "number", min: 1, max: 5 }, { key: "body", label: "بازخورد و توضیح ارزیابی", type: "textarea", wide: true }] },
    interview: { title: item.id ? "ویرایش جلسه مصاحبه" : "برنامه‌ریزی مصاحبه", action: "interview.save", fields: [{ key: "applicantId", label: "متقاضی", options: data.applicants.map(c => ({ value: c.id, label: c.name })) }, { key: "interviewerId", label: "مصاحبه‌کننده", options: staffOptions }, { key: "startsAt", label: "تاریخ و ساعت جلسه", type: "datetime-local", hint: "ساعت محلی مرورگر؛ ذخیره با منطقه زمانی" }, { key: "duration", label: "مدت جلسه (دقیقه)", type: "number", min: 15, max: 240 }, { key: "mode", label: "نوع جلسه", options: options(["حضوری", "آنلاین", "تلفنی", "آزمون عملی"]) }, { key: "status", label: "وضعیت جلسه", options: options({ scheduled: "برنامه‌ریزی‌شده", completed: "برگزار شده", cancelled: "لغو شده" }) }, { key: "location", label: "محل یا لینک جلسه", required: false, wide: true }, { key: "score", label: "امتیاز جلسه (۰ تا ۵)", type: "number", min: 0, max: 5 }, { key: "feedback", label: "بازخورد مصاحبه", type: "textarea", required: false, wide: true }] },
    hire: { title: `شروع همکاری ${item.name || "متقاضی"}`, action: "applicant.hire", fields: [{ key: "code", label: "کد پرسنلی جدید" }, { key: "baseSalary", label: "حقوق پایه توافق‌شده (تومان)", type: "number", min: 1 }, { key: "hireDate", label: "تاریخ شروع همکاری", type: "date" }, { key: "password", label: "رمز اولیه حساب کارمندی", type: "password", hint: "حداقل ۸ نویسه؛ به همکار تحویل داده شود" }, { key: "templateId", label: "ایجاد خودکار برنامه آنبوردینگ", options: [{ value: "", label: "بدون برنامه ورود" }, ...data.templates.map(t => ({ value: t.id, label: t.title }))], required: false, wide: true }] },
    template: { title: item.id ? "ویرایش الگوی آنبوردینگ" : "طراحی یک مسیر خوش‌آمدگویی", action: "template.save", fields: [{ key: "title", label: "نام الگو" }, { key: "department", label: "واحد هدف", options: [{ value: "all", label: "همه واحدها" }, ...departmentOptions] }, { key: "welcome", label: "متن خوش‌آمدگویی و راهنمای روزهای اول", type: "textarea", wide: true }] },
    plan: { title: "آغاز برنامه ورود همکار", action: "plan.create", fields: [{ key: "employeeId", label: "همکار جدید", options: staffOptions }, { key: "templateId", label: "الگوی مسیر ورود", options: data.templates.map(t => ({ value: t.id, label: t.title })) }, { key: "startDate", label: "تاریخ شروع برنامه", type: "date" }] },
    "plan-edit": { title: "شخصی‌سازی برنامه ورود", action: "plan.save", fields: [{ key: "title", label: "عنوان برنامه", wide: true }, { key: "welcome", label: "متن راهنما و خوش‌آمدگویی", type: "textarea", wide: true }] },
    task: { title: item.id ? "ویرایش وظیفه" : "وظیفه جدید در مسیر ورود", action: "task.save", fields: [{ key: "title", label: "عنوان وظیفه", wide: true }, { key: "ownerRole", label: "مسئول انجام", options: options(taskRoleLabels) }, { key: "dueDate", label: "مهلت انجام", type: "date" }] },
    course: { title: item.id ? "ویرایش دوره آموزشی" : "ساخت دوره آموزشی داخلی", action: "course.save", fields: [{ key: "title", label: "عنوان دوره" }, { key: "category", label: "حوزه آموزشی" }, { key: "instructor", label: "مدرس / تولیدکننده محتوا" }, { key: "level", label: "سطح", options: options(["مقدماتی", "متوسط", "پیشرفته"]) }, { key: "status", label: "وضعیت", options: options({ draft: "پیش‌نویس", published: "انتشار", archived: "بایگانی" }) }, { key: "passScore", label: "حدنصاب قبولی از ۱۰۰", type: "number", min: 1, max: 100 }, { key: "description", label: "معرفی و هدف یادگیری", type: "textarea", wide: true }] },
    assign: { title: "تخصیص مسیر یادگیری", action: "enrollment.assign", fields: [{ key: "courseId", label: "دوره", options: data.courses.filter(c => c.status === "published").map(c => ({ value: c.id, label: c.title })) }, { key: "target", label: "شیوه تخصیص", options: options({ single: "یک همکار", department: "کارکنان واحد" }) }, ...(get("target") === "single" ? [{ key: "employeeId", label: "همکار", options: staffOptions }] : [{ key: "department", label: "واحد هدف", options: [{ value: "all", label: "تمام کارکنان در دسترس" }, ...departmentOptions] }]), { key: "dueDate", label: "مهلت تکمیل", type: "date" }] },
    survey: { title: item.id ? "ویرایش پیش‌نویس نظرسنجی" : "صدای تیم را بشنویم", action: "survey.save", fields: [{ key: "title", label: "عنوان نظرسنجی" }, { key: "department", label: "جامعه مخاطب", options: [{ value: "all", label: "تمام کارکنان فعال" }, ...departmentOptions] }, { key: "deadline", label: "پایان مهلت پاسخ", type: "date" }, { key: "description", label: "توضیح برای کارکنان", type: "textarea", wide: true }] },
    improvement: { title: item.id ? "ویرایش اقدام اصلاحی" : "یک قدم برای تجربه بهتر", action: "improvement.save", fields: [{ key: "title", label: "عنوان اقدام", wide: true }, { key: "surveyId", label: "نظرسنجی مرتبط", options: data.surveys.map(s => ({ value: s.id, label: s.title })) }, { key: "employeeId", label: "مسئول پیگیری", options: staffOptions }, { key: "dueDate", label: "مهلت انجام", type: "date" }, { key: "status", label: "وضعیت", options: options({ open: "برنامه‌ریزی‌شده", in_progress: "در حال انجام", done: "انجام شده" }) }, { key: "notes", label: "شرح اقدام و نتیجه", type: "textarea", required: false, wide: true }] },
    policy: { title: "سیاست پرداخت واحد سازمانی", action: "salary.policy", fields: [{ key: "department", label: "واحد سازمانی", options: departmentOptions }, { key: "strategy", label: "استراتژی پرداخت", options: options(strategyLabels) }, { key: "minimum", label: "کف بازه داخلی (تومان)", type: "number", min: 1 }, { key: "midpoint", label: "میانه بازه داخلی (تومان)", type: "number", min: 1 }, { key: "maximum", label: "سقف بازه داخلی (تومان)", type: "number", min: 1 }, { key: "increasePercent", label: "افزایش هدف (درصد)", type: "number", min: 0, max: 100 }, { key: "complexityPercent", label: "ضریب پیچیدگی (درصد)", type: "number", min: 50, max: 200 }, { key: "source", label: "منبع و مبنای بازه", wide: true, hint: "این بازه داخلی است؛ اتصال به داده بازار وجود ندارد." }] },
    simulate: { title: "محاسبه سناریوی جدید حقوق", action: "salary.simulate", fields: [{ key: "title", label: "نام سناریو", wide: true }, { key: "department", label: "محدوده محاسبه", options: [{ value: "all", label: "تمام واحدها" }, ...departmentOptions] }, { key: "employeeId", label: "همکار مشخص (اختیاری)", required: false, options: [{ value: "", label: "تمام همکاران در محدوده انتخابی" }, ...staffOptions] }] },
    rename: { title: "ویرایش عنوان سناریو", action: "salary.rename", fields: [{ key: "title", label: "نام سناریو", wide: true }] },
    confirm: { title: String(item.title || "تأیید عملیات"), action: String(item.action), fields: [] },
  };
  const config = configs[kind];
  async function submit(e: FormEvent) { e.preventDefault(); let payload = { ...values }; if (kind === "interview") payload.startsAt = new Date(get("startsAt")).toISOString(); if (kind === "assign") payload.employeeIds = get("target") === "single" ? [get("employeeId")] : staff.filter(e => get("department") === "all" || e.department === get("department")).map(e => e.id); const result = await mutate(config.action, payload); if (result) close(); }
  function patchList(key: string, index: number, change: Values) { const list = values[key] as Values[]; set(key, list.map((row, i) => i === index ? { ...row, ...change } : row)); }
  function remove(key: string, index: number) { set(key, (values[key] as unknown[]).filter((_, i) => i !== index)); }
  return <Modal title={config.title} subtitle={kind === "confirm" ? undefined : "اطلاعات در پایگاه داده ذخیره می‌شود و سطح دسترسی کنترل خواهد شد."} onClose={close} wide={kind !== "confirm" && kind !== "note" && kind !== "simulate"}><form onSubmit={submit}><div className="modal-body tl-form-body">
    {kind === "confirm" && <div className="confirmation-body"><span className="confirmation-icon"><ShieldCheck size={27} /></span><p>{String(item.description || "آیا از انجام این عملیات مطمئن هستید؟")}</p></div>}
    <div className="form-grid">{config.fields.map(f => <Field key={f.key} label={f.label} hint={f.hint} className={f.wide ? "tl-wide" : ""}>{f.options ? <select required={f.required !== false} value={get(f.key)} onChange={e => set(f.key, e.target.value)}>{f.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select> : f.type === "textarea" ? <textarea required={f.required !== false} rows={4} value={get(f.key)} onChange={e => set(f.key, e.target.value)} /> : f.type === "date" ? <JalaliDatePicker value={get(f.key)} onChange={v => set(f.key, v)} ariaLabel={f.label} required={f.required !== false} /> : f.type === "datetime-local" ? <JalaliDateTimePicker value={get(f.key)} onChange={v => set(f.key, v)} ariaLabel={f.label} /> : <input type={f.type || "text"} required={f.required !== false} value={get(f.key)} min={f.min} max={f.max || (f.type === "number" ? 1000000000 : undefined)} minLength={f.type === "password" ? 8 : undefined} autoComplete={f.type === "password" ? "new-password" : "off"} onChange={e => set(f.key, e.target.value)} />}</Field>)}</div>
    {kind === "template" && <section className="tl-builder"><h3>چک‌لیست وظایف الگو <small>روز صفر = تاریخ شروع برنامه</small></h3>{(values.tasks as TaskSpec[]).map((task, i) => <div className="tl-builder-row" key={i}><span className="tl-number">{fa(i + 1)}</span><input aria-label={`عنوان وظیفه ${i + 1}`} placeholder="عنوان وظیفه" required value={task.title} onChange={e => patchList("tasks", i, { title: e.target.value })} /><select aria-label="مسئول وظیفه" value={task.ownerRole} onChange={e => patchList("tasks", i, { ownerRole: e.target.value })}>{Object.entries(taskRoleLabels).map(([k, value]) => <option key={k} value={k}>{value}</option>)}</select><input aria-label="روز نسبت به شروع" type="number" min={-30} max={180} required value={task.offsetDays} onChange={e => patchList("tasks", i, { offsetDays: Number(e.target.value) })} className="tl-number-input" /><button type="button" aria-label="حذف وظیفه الگو" className="icon-button danger-hover" disabled={(values.tasks as TaskSpec[]).length <= 1} onClick={() => remove("tasks", i)}><Trash2 size={15} /></button></div>)}<button type="button" className="text-button" onClick={() => set("tasks", [...values.tasks as TaskSpec[], { title: "", ownerRole: "employee", offsetDays: 1 }])}><Plus size={15} />افزودن وظیفه</button><p className="field-note">ویرایش الگو، برنامه‌های قبلاً ایجادشده را تغییر نمی‌دهد.</p></section>}
    {kind === "course" && <><section className="tl-builder"><h3>فصل‌های مسیر یادگیری</h3>{(values.lessons as Lesson[]).map((lesson, i) => <div className="tl-builder-card" key={lesson.id}><div className="tl-builder-title"><strong>درس {fa(i + 1)}</strong><button type="button" className="icon-button danger-hover" aria-label="حذف درس" disabled={(values.lessons as Lesson[]).length <= 1} onClick={() => remove("lessons", i)}><Trash2 size={15} /></button></div><div className="form-grid"><Field label="عنوان درس"><input required value={lesson.title} onChange={e => patchList("lessons", i, { title: e.target.value })} /></Field><Field label="زمان مطالعه (دقیقه)"><input type="number" min={1} max={1000} required value={lesson.minutes} onChange={e => patchList("lessons", i, { minutes: Number(e.target.value) })} /></Field><Field label="محتوای آموزشی" className="tl-wide"><textarea required rows={4} value={lesson.content} onChange={e => patchList("lessons", i, { content: e.target.value })} /></Field><Field label="پیوند تکمیلی ویدیو یا فایل (اختیاری)" className="tl-wide"><input type="url" value={lesson.url} onChange={e => patchList("lessons", i, { url: e.target.value })} placeholder="https://..." dir="ltr" /></Field></div></div>)}<button type="button" className="text-button" onClick={() => set("lessons", [...values.lessons as Lesson[], { id: crypto.randomUUID(), title: "", content: "", minutes: 15, url: "" }])}><Plus size={15} />افزودن درس</button></section><section className="tl-builder"><h3>آزمون پایان دوره</h3>{(values.quiz as QuizQuestion[]).map((q, i) => <div className="tl-builder-card" key={q.id}><div className="tl-builder-title"><strong>سؤال {fa(i + 1)}</strong><button type="button" aria-label="حذف سؤال آزمون" className="icon-button danger-hover" disabled={(values.quiz as QuizQuestion[]).length <= 1} onClick={() => remove("quiz", i)}><Trash2 size={15} /></button></div><Field label="صورت سؤال"><input required value={q.text} onChange={e => patchList("quiz", i, { text: e.target.value })} /></Field><div className="tl-quiz-options">{q.options.map((option, n) => <label key={n}><input type="radio" name={`correct-${q.id}`} checked={q.correct === n} onChange={() => patchList("quiz", i, { correct: n })} aria-label={`گزینه صحیح ${n + 1}`} /><input required placeholder={`گزینه ${fa(n + 1)}`} aria-label={`متن گزینه ${n + 1}`} value={option} onChange={e => patchList("quiz", i, { options: q.options.map((o, x) => n === x ? e.target.value : o) })} /></label>)}</div><small className="field-note">دایره کنار پاسخ صحیح را انتخاب کنید.</small></div>)}<button type="button" className="text-button" onClick={() => set("quiz", [...values.quiz as QuizQuestion[], { id: crypto.randomUUID(), text: "", options: ["", "", ""], correct: 0 }])}><Plus size={15} />افزودن سؤال</button></section><div className="inline-info"><Info size={16} />پس از تخصیص، درس‌ها و آزمون برای حفظ اعتبار کارنامه قفل می‌شوند؛ عنوان و وضعیت همچنان قابل تغییر است.</div></>}
    {kind === "survey" && <section className="tl-builder"><h3>طراحی پرسش‌نامه</h3>{(values.questions as SurveyQuestion[]).map((q, i) => <div className="tl-builder-card" key={q.id}><div className="tl-builder-title"><strong>پرسش {fa(i + 1)}</strong><button type="button" aria-label="حذف پرسش" className="icon-button danger-hover" disabled={(values.questions as SurveyQuestion[]).length <= 1} onClick={() => remove("questions", i)}><Trash2 size={15} /></button></div><Field label="متن پرسش"><input required value={q.text} onChange={e => patchList("questions", i, { text: e.target.value })} /></Field><div className="form-grid spaced-field"><Field label="نوع پاسخ"><select value={q.type} onChange={e => patchList("questions", i, { type: e.target.value })}><option value="scale">مقیاس رضایت ۱ تا ۵</option><option value="enps">توصیه همکاری eNPS از ۰ تا ۱۰</option></select></Field><Field label="شاخص مورد سنجش"><input required value={q.dimension} onChange={e => patchList("questions", i, { dimension: e.target.value })} /></Field></div></div>)}<button type="button" className="text-button" onClick={() => set("questions", [...values.questions as SurveyQuestion[], { id: crypto.randomUUID(), text: "", type: "scale", dimension: "" }])}><Plus size={15} />افزودن پرسش</button><div className="inline-info"><ShieldCheck size={17} />گزارش فقط پس از بستن نظرسنجی و با حداقل ۵ پاسخ در هر گروه منتشر می‌شود؛ نام پاسخ‌دهندگان در نتایج نمایش داده نمی‌شود.</div></section>}
    {kind === "simulate" && <div className="inline-info"><Info size={17} />محاسبه بر اساس بازه‌ها و سیاست‌های داخلی است، نه هوش مصنوعی یا داده زنده بازار. تا تأیید مدیر، حقوق پایه هیچ فردی تغییر نمی‌کند.</div>}
    {kind === "hire" && <div className="inline-info"><ShieldCheck size={17} />پرونده پرسنلی، حساب کارمندی و برنامه ورود انتخاب‌شده در یک تراکنش ایجاد می‌شوند.</div>}
  </div><div className="modal-footer"><button type="button" className="btn secondary" onClick={close} disabled={busy}>انصراف</button><SubmitButton busy={busy}>{kind === "hire" ? "تأیید استخدام و ایجاد حساب" : kind === "simulate" ? "محاسبه و ذخیره سناریو" : kind === "confirm" ? "تأیید و ادامه" : "ذخیره تغییرات"}<Check size={16} /></SubmitButton></div></form></Modal>;
}
