"use client";
import { useState } from "react";
import { ArrowLeft, ArrowUpLeft, BookOpen, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronLeft, ClipboardCheck, ExternalLink, FileSearch, GraduationCap, HeartPulse, Layers, Rocket, Search, ShieldCheck, Sparkles, Users, Wallet } from "lucide-react";
import { useWorkspace } from "@/components/workspace-context";
import { PageHeading, RelativeTime } from "@/components/ui";
import { fa, type Page } from "@/lib/types";
import { reviewSources, featureGroups } from "@/lib/cando-review";
import { useTalent } from "./context";
import { SectionHead, TalentStats } from "./shared";
const modules = [
  { page: "recruitment" as Page, title: "استعدادهای تازه، تیمی قوی‌تر", label: "جذب و استخدام", english: "APPLICANT TRACKING", description: "از بانک رزومه و مصاحبه تا پیشنهاد همکاری؛ همه مراحل جذب را یکجا پیش ببرید.", Icon: BriefcaseBusiness, color: "teal", roles: ["admin", "manager"] },
  { page: "onboarding" as Page, title: "یک شروع خوب، یک همراهی ماندگار", label: "آنبوردینگ", english: "A BETTER FIRST DAY", description: "مسیر ورود شخصی‌سازی‌شده، وظایف روشن و یک خوش‌آمدگویی گرم برای هر همکار.", Icon: Rocket, color: "blue", roles: ["admin", "manager", "finance", "employee"] },
  { page: "learning" as Page, title: "یادگیری، در جریان هر روز", label: "آکادمی آبان", english: "LEARNING & GROWTH", description: "دوره‌های اختصاصی بسازید، مسیر یادگیری تعریف کنید و رشد مهارت‌ها را ببینید.", Icon: GraduationCap, color: "purple", roles: ["admin", "manager", "finance", "employee"] },
  { page: "pulse" as Page, title: "صدای تیم را بهتر بشنوید", label: "نبض سازمان", english: "LISTEN. LEARN. IMPROVE.", description: "بازخوردهای بی‌نام را به شناخت بهتر و اقدام‌های کوچک اما مؤثر تبدیل کنید.", Icon: HeartPulse, color: "rose", roles: ["admin", "manager", "finance", "employee"] },
  { page: "compensation" as Page, title: "تصمیم روشن برای پرداخت منصفانه", label: "دستیار تعیین حقوق", english: "TRANSPARENT COMPENSATION", description: "سیاست پرداخت تیم‌ها را تعریف و اثر سناریوهای حقوق را پیش از تأیید بررسی کنید.", Icon: Wallet, color: "orange", roles: ["admin", "finance"] },
];
export function GrowthRibbon() { const { navigate, data } = useWorkspace(); return <div className="tl-growth-ribbon"><span className="tl-ribbon-icon"><Sparkles size={20} /></span><div><strong>فصل تازه‌ای از همراهی در آبان</strong><span>جذب، ورود، یادگیری و شنیدن صدای تیم؛ حالا در یک مسیر.</span></div><span className="tl-new-pill">جدید</span><button onClick={() => navigate("talent")}>کشف امکانات رشد تیم<ArrowLeft size={15} /></button></div>; }
export function TalentHub() {
  const { data, open } = useTalent(); const { data: workspace, navigate } = useWorkspace(); const mine = workspace.user.role === "employee"; const visible = modules.filter(m => m.roles.includes(workspace.user.role)); const pendingTasks = data.tasks.filter(t => !t.done).length;
  return <div className="tl-page page-enter"><PageHeading eyebrow="نسخه تازه آبان" title="رشد و تجربه کارکنان" subtitle="همراه تمام لحظه‌های همکاری؛ از اولین آشنایی تا رشد و ماندگاری."><button className="btn secondary" onClick={() => navigate("research")}><FileSearch size={16} />گزارش بررسی و قابلیت‌ها</button><button className="btn primary" onClick={() => navigate(mine ? "learning" : "onboarding")}><PlusIcon />{mine ? "مسیر یادگیری من" : "شروع یک همراهی تازه"}</button></PageHeading>
    <section className="tl-hub-hero"><div className="tl-hub-hero-copy"><span><i />جریان رشد، در کنار هم</span><h2>برای هر مرحله از مسیر،<br />یک تجربه بهتر بسازید.</h2><p>ابزارهای تازه آبان، کارهای پراکنده منابع انسانی را<br />به یک مسیر پیوسته و انسانی تبدیل می‌کنند.</p><div className="tl-hero-checks"><span><CheckCircle2 size={13} />یکپارچه با پرونده پرسنلی</span><span><ShieldCheck size={13} />دسترسی متناسب با نقش</span></div></div><div className="tl-lifecycle-art" aria-hidden="true"><div className="tl-cycle-ring" /><div className="tl-cycle-center"><Users size={37} strokeWidth={1.4} /><strong>همراهِ تیم</strong><span>ABAN PEOPLE</span></div><span className="tl-cycle-node node-1"><BriefcaseBusiness size={23} /></span><span className="tl-cycle-node node-2"><Rocket size={24} /></span><span className="tl-cycle-node node-3"><GraduationCap size={25} /></span><span className="tl-cycle-node node-4"><HeartPulse size={23} /></span><span className="tl-cycle-node node-5"><Wallet size={23} /></span><div className="tl-cycle-label">همه‌چیز از آدم‌ها شروع می‌شود <Sparkles size={13} /></div></div></section>
    <TalentStats items={[{ title: "فرصت‌های تازه", value: data.jobs.filter(j => j.status === "open").length, detail: "جذب همکاران آینده", icon: BriefcaseBusiness }, { title: "قدم‌های پیش روی تیم", value: pendingTasks, detail: "وظایف باز آنبوردینگ", icon: ClipboardCheck, color: "blue" }, { title: "مسیرهای یادگیری", value: data.courses.filter(c => c.status === "published").length, detail: "محتوای اختصاصی مجموعه", icon: GraduationCap, color: "purple" }, { title: "فرصت شنیده‌شدن", value: data.surveys.filter(s => s.status === "active").length, detail: "نظرسنجی فعال", icon: HeartPulse, color: "orange" }]} />
    <SectionHead title="یک چرخه کامل، یک فضای یکپارچه" subtitle="ابزار مناسب برای هر لحظه از تجربه کارکنان" /><div className="tl-modules-grid">{visible.map(m => <button className={`card tl-module-card module-${m.color}`} key={m.page} onClick={() => navigate(m.page)}><div className="tl-module-card-top"><span className={`tl-module-icon ${m.color}`}><m.Icon size={25} strokeWidth={1.55} /></span><span className="tl-module-english">{m.english}</span><ArrowUpLeft size={17} /></div><span className="tl-module-name">{m.label}</span><h3>{m.title}</h3><p>{m.description}</p><div><span>ورود به {m.label}</span><ArrowLeft size={15} /></div></button>)}<button className="card tl-module-card tl-research-card" onClick={() => navigate("research")}><div className="tl-module-card-top"><span className="tl-module-icon neutral"><FileSearch size={25} /></span><span className="tl-module-english">BUILT WITH CLARITY</span><ArrowUpLeft size={17} /></div><span className="tl-module-name">شفافیت در توسعه</span><h3>چه چیزی بررسی و اضافه شده؟</h3><p>جزئیات تطبیق با صفحات عمومی کندو، امکانات پیاده‌شده و مرز اتصال‌های بیرونی.</p><div><span>مشاهده گزارش بررسی</span><ArrowLeft size={15} /></div></button></div>
    <section className="card tl-hub-activity"><SectionHead title="جریان تازه فعالیت‌ها" subtitle="رویدادهای مربوط به فضای کاری شما" /><div>{data.activity.slice(0, 4).map(a => <div className="tl-hub-event" key={a.id}><span><CheckCircle2 size={17} /></span><div><p>{a.title}</p><small>{a.actorName}</small></div><time><RelativeTime date={a.createdAt} /></time></div>)}{!data.activity.length && <p className="tl-page-note">فعالیت‌های جدید اینجا ثبت خواهند شد.</p>}</div></section><p className="tl-page-note">امکانات مرخصی، امکانات رفاهی، مساعده و حقوق و دستمزد قبلی همچنان در منوی اصلی در دسترس هستند.</p></div>;
}
function PlusIcon() { return <Sparkles size={16} />; }
export function ResearchPage() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const all = featureGroups.flatMap(g => g.features); const done = all.filter(f => f.status === "done").length;
  return <div className="tl-page page-enter"><PageHeading eyebrow="گزارش بررسی منابع عمومی" title="از بررسی کندو تا توسعه آبان" subtitle="تطبیق شفاف قابلیت‌ها؛ پیاده‌سازی مستقل با حفظ هویت و اطلاعات آبان."><a className="btn secondary" href="https://hrcando.ir/" target="_blank" rel="noopener noreferrer">وب‌سایت مبنا<ExternalLink size={15} /></a></PageHeading><div className="tl-research-intro card"><span className="tl-module-icon teal"><FileSearch size={29} /></span><div><h2>چه چیزی را بررسی کردیم؟</h2><p>صفحه اصلی، پنج صفحه محصول، راهنمای فایل کارجو، گزارش استخدام داده‌محور و سیاست محرمانگی بررسی شده‌اند. این بررسی به محتوای عمومی محدود است؛ به پنل تجاری، کد خصوصی، داده مشتریان و مدل‌های اختصاصی کندو دسترسی نداشته‌ایم.</p></div></div><TalentStats items={[{ title: "صفحه عمومی بررسی‌شده", value: reviewSources.length, icon: FileSearch }, { title: "محور محصول", value: featureGroups.length, icon: Layers, color: "blue" }, { title: "قابلیت پیاده‌سازی‌شده", value: done, icon: CheckCircle2, color: "purple" }, { title: "موارد نیازمند اتصال بیرونی", value: all.filter(f => f.status === "external").length, icon: ExternalLink, color: "orange" }]} />
    <div className="card tl-workspace"><div className="tl-toolbar"><div className="input-search"><Search size={16} /><input aria-label="جستجوی قابلیت" placeholder="جستجوی قابلیت یا جزئیات پیاده‌سازی..." value={query} onChange={e => setQuery(e.target.value)} /></div><select aria-label="وضعیت قابلیت" value={status} onChange={e => setStatus(e.target.value)}><option value="all">تمام وضعیت‌ها</option><option value="done">پیاده‌سازی‌شده</option><option value="adapted">نسخه متناسب با آبان</option><option value="external">نیازمند سرویس یا مجوز</option></select></div><div className="tl-feature-groups">{featureGroups.map(g => { const features = g.features.filter(f => (status === "all" || f.status === status) && `${f.title} ${f.implementation}`.includes(query)); if (!features.length) return null; return <section key={g.id}><SectionHead title={g.title} subtitle={g.description}><a className="text-button" href={reviewSources[g.source].url} target="_blank" rel="noopener noreferrer">منبع عمومی<ExternalLink size={13} /></a></SectionHead>{features.map(f => <details key={f.title} className="tl-feature-row" open><summary><span className={`tl-feature-dot ${f.status}`} />{f.title}<span className={`badge ${f.status === "done" ? "green" : f.status === "adapted" ? "blue" : "amber"}`}>{f.status === "done" ? "پیاده‌سازی‌شده" : f.status === "adapted" ? "متناسب با آبان" : "نیازمند اتصال / مجوز"}</span><ChevronLeft size={14} /></summary><p>{f.implementation}</p></details>)}</section>; })}</div></div><section className="card tl-research-sources"><SectionHead title="منابع بررسی" subtitle="پیوند مستقیم صفحات عمومی مبنا" />{reviewSources.map((s, i) => <a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer"><span>{fa(i + 1)}</span><div><strong>{s.title}</strong><p>{s.scope}</p></div><ExternalLink size={16} /></a>)}</section><div className="calculation-note"><ShieldCheck size={18} /><p>هیچ داده کارمند یا متقاضی به کندو، جاب‌ویژن یا مکتب‌خونه ارسال نمی‌شود. نشان تجاری، تصاویر محصول و محتوای خصوصی آن‌ها کپی نشده‌اند. قابلیت‌های پیاده‌نشده به‌عنوان فعال نمایش داده نمی‌شوند.</p></div></div>;
}
