"use client";
import { useState } from "react";
import { ArrowLeft, ArrowUpLeft, BriefcaseBusiness, CalendarDays, Clock3, Download, ExternalLink, FileText, Filter, LayoutGrid, List, MapPin, Plus, Star, Users, UserRoundCheck, Wallet } from "lucide-react";
import { useWorkspace } from "@/components/workspace-context";
import { Avatar, EmptyState, PageHeading, Pagination } from "@/components/ui";
import { EmployeesPage } from "@/components/resource-pages";
import { dateFa, fa, money } from "@/lib/types";
import { stages, sourceLabels } from "@/lib/talent-types";
import { useTalent } from "./context";
import { EntityActions, SectionHead, StateTag, TalentSearch, TalentStats, TalentTabs } from "./shared";
export function RecruitmentPage() {
  const { data, open, mutate, busy } = useTalent(); const { data: workspace } = useWorkspace(); const [tab, setTab] = useState("board"); const [query, setQuery] = useState(""); const [jobId, setJobId] = useState("all"); const [source, setSource] = useState("all"); const [page, setPage] = useState(1); const [drag, setDrag] = useState("");
  const applicants = data.applicants.filter(c => (jobId === "all" || c.jobId === jobId) && (source === "all" || c.source === source) && `${c.name} ${c.email} ${c.skills} ${c.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  const hires = data.applicants.filter(c => c.stage === "hired"); const upcoming = data.interviews.filter(i => i.status === "scheduled" && Date.parse(i.startsAt) >= Date.now());
  const reviewCandidate = (id: string) => { const c = data.applicants.find(c => c.id === id); if (c) open("applicant-detail", c); };
  async function move(id: string, stage: string) { const c = data.applicants.find(c => c.id === id); if (!c || c.stage === stage) return; if (stage === "hired") { if (workspace.user.role === "admin") open("hire", c); return; } await mutate("applicant.move", { id, stage, fromStage: c.stage }, "مرحله متقاضی به‌روزرسانی شد."); }
  return <div className="tl-page page-enter"><PageHeading eyebrow="جذب استعدادهای تازه" title="جذب و استخدام" subtitle="از اولین رزومه تا اولین روز همکاری؛ یک مسیر روشن برای تیم جذب."><a className="btn secondary" href="/careers" target="_blank" rel="noopener noreferrer"><ExternalLink size={15} />صفحه فرصت‌های همکاری</a><button className="btn primary" onClick={() => open("job")}><Plus size={16} />فرصت شغلی جدید</button></PageHeading>
    <TalentStats items={[{ title: "فرصت‌های شغلی فعال", value: data.jobs.filter(j => j.status === "open").length, detail: "در انتظار همکاران آینده", icon: BriefcaseBusiness }, { title: "رزومه‌های دریافت‌شده", value: data.applicants.length, detail: "در بانک استعدادهای آبان", icon: Users, color: "blue" }, { title: "مصاحبه‌های پیش رو", value: upcoming.length, detail: "هماهنگی برای شناخت بیشتر", icon: CalendarDays, color: "purple" }, { title: "همکاری‌های آغازشده", value: hires.length, detail: "متصل به پرونده پرسنلی", icon: UserRoundCheck, color: "orange" }]} />
    <div className="card tl-workspace"><TalentTabs active={tab} onChange={v => { setTab(v); setQuery(""); setPage(1); }} tabs={[{ id: "board", label: "برد استخدام" }, { id: "candidates", label: "بانک رزومه", count: data.applicants.length }, { id: "jobs", label: "فرصت‌های شغلی" }, { id: "interviews", label: "مصاحبه‌ها" }, { id: "analytics", label: "گزارش جذب" }, { id: "legacy", label: "پرونده‌های قبلی" }]} />
    {["board", "candidates"].includes(tab) && <><TalentSearch value={query} onChange={v => { setQuery(v); setPage(1); }} placeholder="جستجوی نام، مهارت یا برچسب..."><select aria-label="فیلتر فرصت شغلی" value={jobId} onChange={e => { setJobId(e.target.value); setPage(1); }}><option value="all">همه فرصت‌ها</option>{data.jobs.map(j => <option key={j.id} value={j.id}>{j.title}</option>)}</select><select aria-label="منبع جذب" value={source} onChange={e => { setSource(e.target.value); setPage(1); }}><option value="all">همه منابع</option>{sourceLabels.map(s => <option key={s}>{s}</option>)}</select><button className="btn small primary tl-toolbar-end" onClick={() => open("applicant", undefined, jobId === "all" ? undefined : { jobId })}><Plus size={14} />افزودن متقاضی</button><a className="icon-button" href="/api/talent/export?type=recruitment" title="خروجی اکسل" aria-label="خروجی بانک رزومه"><Download size={17} /></a></TalentSearch>
    {tab === "board" ? <><div className="tl-board" aria-label="برد مراحل استخدام">{stages.map(stage => <section key={stage.id} className={`tl-column ${drag === stage.id ? "drag-over" : ""}`} onDragOver={e => { e.preventDefault(); if (!busy) setDrag(stage.id); }} onDragLeave={() => setDrag("")} onDrop={e => { e.preventDefault(); setDrag(""); if (!busy) void move(e.dataTransfer.getData("text/plain"), stage.id); }}><div className="tl-column-head"><span><i style={{ background: stage.color }} />{stage.label}<b>{fa(applicants.filter(c => c.stage === stage.id).length)}</b></span><button aria-label={`افزودن متقاضی ${stage.label}`} onClick={() => open("applicant", undefined, jobId !== "all" ? { jobId } : {})}><Plus size={15} /></button></div><div className="tl-column-cards">{applicants.filter(c => c.stage === stage.id).map(c => <button className="tl-candidate-card" key={c.id} draggable={c.stage !== "hired" && !busy} onDragStart={e => e.dataTransfer.setData("text/plain", c.id)} onClick={() => reviewCandidate(c.id)}><div className="tl-candidate-top"><Avatar name={c.name} /><span><strong>{c.name}</strong><small>{data.jobs.find(j => j.id === c.jobId)?.title}</small></span><ArrowUpLeft size={14} /></div><div className="tl-candidate-tags">{c.tags.slice(0, 2).map(t => <span key={t}>{t}</span>)}</div><div className="tl-candidate-meta"><span><BriefcaseBusiness size={12} />{fa(c.experience)} سال تجربه</span><span><Star size={12} fill={c.rating ? "#dfba6c" : "none"} />{fa(c.rating)} / ۵</span></div><div className="tl-candidate-footer"><span>{c.source.replace(" (ثبت دستی)", "")}</span><span>{dateFa(c.createdAt)}</span></div></button>)}{!applicants.some(c => c.stage === stage.id) && <div className="tl-column-empty"><Users size={24} /><span>هنوز متقاضی‌ای در این مرحله نیست</span></div>}</div></section>)}</div><p className="tl-board-hint"><InfoIcon />کارت‌ها را جابه‌جا کنید یا از جزئیات متقاضی مرحله را تغییر دهید. استخدام نهایی نیازمند ایجاد حساب کارمندی است.</p></> : applicants.length ? <><div className="table-scroll"><table className="data-table"><thead><tr><th>متقاضی</th><th>فرصت شغلی</th><th>منبع</th><th>مرحله</th><th>امتیاز</th><th /></tr></thead><tbody>{applicants.slice((page - 1) * 10, page * 10).map(c => <tr key={c.id}><td><button className="person-cell person-button" onClick={() => reviewCandidate(c.id)}><Avatar name={c.name} /><span><strong>{c.name}</strong><small>{c.email}</small></span></button></td><td>{data.jobs.find(j => j.id === c.jobId)?.title}</td><td>{c.source}</td><td><span className="badge blue">{stages.find(s => s.id === c.stage)?.label}</span></td><td><Star size={12} /> {fa(c.rating)}</td><td><button className="btn small secondary" onClick={() => reviewCandidate(c.id)}>بررسی<ArrowLeft size={13} /></button></td></tr>)}</tbody></table></div><Pagination page={page} count={applicants.length} onChange={setPage} /></> : <EmptyState title="رزومه‌ای با این مشخصات پیدا نشد" description="فیلترها را تغییر دهید یا یک متقاضی جدید ثبت کنید." />}</>}
    {tab === "jobs" && <div className="tl-padded"><SectionHead title="فرصت‌های همکاری" subtitle="آگهی‌های باز به‌صورت خودکار در صفحه عمومی مجموعه دیده می‌شوند." /><div className="tl-job-grid">{data.jobs.map(j => <article className="tl-job-card" key={j.id}><div className="tl-job-card-top"><span className="tl-module-icon teal"><BriefcaseBusiness size={24} /></span><StateTag status={j.status} /></div><h3>{j.title}</h3><p>{j.department}</p><div className="tl-job-meta"><span><MapPin size={13} />{j.location}</span><span><Clock3 size={13} />{j.contract}</span></div><div className="tl-job-count"><span><Users size={15} />{fa(data.applicants.filter(c => c.jobId === j.id).length)} متقاضی</span><span>{fa(j.openings)} ظرفیت</span></div><div className="tl-job-bottom"><button className="text-button" onClick={() => { setJobId(j.id); setTab("board"); }}>مشاهده مسیر جذب<ArrowLeft size={13} /></button><EntityActions kind="job" item={j} deleteAction="job.delete" /></div></article>)}</div>{!data.jobs.length && <EmptyState action="فرصت شغلی جدید" onAction={() => open("job")} />}</div>}
    {tab === "interviews" && <div className="tl-padded"><SectionHead title="قرارهای آشنایی" subtitle="تداخل زمانی مصاحبه‌کننده در سرور کنترل می‌شود."><button className="btn small primary" onClick={() => open("interview")}><Plus size={15} />برنامه‌ریزی مصاحبه</button></SectionHead>{data.interviews.length ? <div className="tl-interview-list">{data.interviews.map(i => { const c = data.applicants.find(c => c.id === i.applicantId); return <div className="tl-interview-row" key={i.id}><div className="tl-calendar-tile"><strong>{new Intl.DateTimeFormat("fa-IR", { day: "numeric" }).format(new Date(i.startsAt))}</strong><span>{new Intl.DateTimeFormat("fa-IR", { month: "short" }).format(new Date(i.startsAt))}</span></div><div className="tl-interview-description"><button onClick={() => reviewCandidate(i.applicantId)}><strong>{c?.name}</strong><ArrowUpLeft size={13} /></button><small>{data.jobs.find(j => j.id === c?.jobId)?.title} · {workspace.employees.find(e => e.id === i.interviewerId)?.name}</small></div><div className="tl-interview-time"><strong>{new Intl.DateTimeFormat("fa-IR", { hour: "2-digit", minute: "2-digit" }).format(new Date(i.startsAt))}</strong><small>{fa(i.duration)} دقیقه · {i.mode}</small></div><StateTag status={i.status} /><a className="icon-button" href={`/api/talent/export?type=calendar&id=${i.id}`} aria-label="افزودن به تقویم" title="دریافت فایل تقویم"><CalendarDays size={18} /></a><EntityActions kind="interview" item={i} deleteAction="interview.delete" /></div>; })}</div> : <EmptyState title="قرار آشنایی بعدی را برنامه‌ریزی کنید" action="ثبت مصاحبه" onAction={() => open("interview")} />}</div>}
    {tab === "analytics" && <div className="tl-padded"><SectionHead title="از داده به تصمیم بهتر" subtitle="تمام شاخص‌ها از پرونده‌های همین مجموعه محاسبه می‌شوند؛ مقایسه بازار نیست." /><div className="tl-analytics-grid"><section><h3>قیف وضعیت فعلی جذب</h3><div className="tl-funnel">{stages.map(s => { const count = data.applicants.filter(c => c.stage === s.id).length; return <div key={s.id}><span>{s.label}</span><div><i style={{ width: `${Math.max(3, count / Math.max(1, data.applicants.length) * 100)}%`, background: s.color }} /></div><b>{fa(count)}</b></div>; })}</div></section><section><h3>منابع جذب استعداد</h3>{[...new Set(data.applicants.map(c => c.source))].map(source => <div className="tl-source-row" key={source}><span>{source}</span><strong>{fa(data.applicants.filter(c => c.source === source).length)} <small>رزومه</small></strong></div>)}</section></div><div className="tl-insight-strip"><span>میانگین زمان جذب <strong>{hires.length ? `${fa(Math.round(hires.reduce((n, c) => n + (Date.parse(c.updatedAt) - Date.parse(c.createdAt)) / 86400000, 0) / hires.length))} روز` : "پس از اولین استخدام"}</strong></span><span>هزینه ثبت‌شده به ازای استخدام <strong>{hires.length ? money(Math.round(data.jobs.reduce((n, j) => n + j.hiringCost, 0) / hires.length)) : "پس از اولین استخدام"}</strong></span><a className="btn secondary" href="/api/talent/export?type=recruitment"><Download size={16} />گزارش اکسل جذب</a></div></div>}
    {tab === "legacy" && <div className="tl-padded"><p className="inline-info">پرونده‌های متقاضیان نسخه قبلی بدون تغییر حفظ شده‌اند. مسیرهای جدید در بانک رزومه مدیریت می‌شوند.</p><EmployeesPage recruitment /></div>}
    </div></div>;
}
function InfoIcon() { return <FileText size={14} />; }
