"use client";
import type { ReactNode } from "react";
import { ArrowUpLeft, Search, Plus, Trash2, Pencil, MoreHorizontal, type LucideIcon } from "lucide-react";
import { useTalent } from "./context";
import { fa } from "@/lib/types";
export function TalentStats({ items }: { items: { title: string; value: string | number; detail?: string; icon: LucideIcon; color?: string }[] }) { return <div className="tl-stats">{items.map(({ title, value, detail, icon: Icon, color = "teal" }) => <div className="card tl-stat" key={title}><span className={`tl-stat-icon ${color}`}><Icon size={21} strokeWidth={1.6} /></span><div><span>{title}</span><strong>{typeof value === "number" ? fa(value) : value}</strong>{detail && <small>{detail}</small>}</div></div>)}</div>; }
export function Progress({ value, label = true }: { value: number; label?: boolean }) { return <div className="tl-progress-wrap"><div className="tl-progress" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><i style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>{label && <span>{fa(value)}٪</span>}</div>; }
export function TalentTabs({ tabs, active, onChange }: { tabs: { id: string; label: string; count?: number }[]; active: string; onChange: (id: string) => void }) { return <div className="tl-tabs" role="tablist">{tabs.map(t => <button key={t.id} role="tab" aria-selected={active === t.id} className={active === t.id ? "active" : ""} onClick={() => onChange(t.id)}>{t.label}{t.count !== undefined && <span>{fa(t.count)}</span>}</button>)}</div>; }
export function TalentSearch({ value, onChange, placeholder = "جستجو...", children }: { value: string; onChange: (value: string) => void; placeholder?: string; children?: ReactNode }) { return <div className="tl-toolbar"><div className="input-search"><Search size={16} /><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e => onChange(e.target.value)} /></div>{children}</div>; }
export function EntityActions({ kind, item, deleteAction, canEdit = true }: { kind: string; item: { id: string; title?: string }; deleteAction?: string; canEdit?: boolean }) { const { open } = useTalent(); if (!canEdit) return null; return <div className="row-actions"><button className="icon-button" aria-label={`ویرایش ${item.title || "مورد"}`} onClick={() => open(kind, item)}><Pencil size={15} /></button>{deleteAction && <button className="icon-button danger-hover" aria-label={`حذف ${item.title || "مورد"}`} onClick={() => open("confirm", { action: deleteAction, id: item.id, title: "حذف مورد انتخاب‌شده", description: "این عملیات قابل بازگشت نیست. موارد دارای سوابق نهایی‌شده حذف نخواهند شد." })}><Trash2 size={15} /></button>}</div>; }
export function StateTag({ status }: { status: string }) { const labels: Record<string, string> = { draft: "پیش‌نویس", open: "فعال", active: "در حال اجرا", closed: "پایان‌یافته", published: "منتشرشده", archived: "بایگانی", scheduled: "برنامه‌ریزی‌شده", completed: "تکمیل‌شده", cancelled: "لغو شده", assigned: "شروع نشده", in_progress: "در حال انجام", done: "انجام شده", applied: "اعمال‌شده" }; return <span className={`badge ${["open", "published", "completed", "applied", "done"].includes(status) ? "green" : ["active", "in_progress", "scheduled"].includes(status) ? "blue" : "gray"}`}><i />{labels[status] || status}</span>; }
export function SectionHead({ title, subtitle, children }: { title: string; subtitle?: string; children?: ReactNode }) { return <div className="tl-section-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{children}</div>; }
