"use client";
import { useMemo, useState } from "react";
import { ArrowDownToLine, ArrowLeft, ArrowUpLeft, ArrowUpRight, CalendarCheck2, CalendarDays, ChartNoAxesCombined, ChartPie, ChevronLeft, CircleDollarSign, Clock3, FileSpreadsheet, Gift, Plus, Sparkles, Users, Wallet, Zap } from "lucide-react";
import { GrowthRibbon } from "@/components/talent/hub";
import { useWorkspace } from "@/components/workspace-context";
import { Avatar, EmptyState, PageHeading, RelativeTime, StatusBadge } from "@/components/ui";
import { dateFa, departments, fa, getPeriod, money, requestLabels, type Request } from "@/lib/types";

function RequestsChart() {
  const { data } = useWorkspace(); const [range, setRange] = useState("30"); const [hover, setHover] = useState<number | null>(null);
  const chart = useMemo(() => { const days = Number(range); const count = days === 7 ? 7 : 6; const step = days / count; const now = Date.now(); return Array.from({ length: count }, (_, i) => { const start = now - (count - i) * step * 86400000; const end = now - (count - i - 1) * step * 86400000; const records = data.requests.filter(r => { const time = Date.parse(r.createdAt); return time >= start && time <= end; }); return { leave: records.filter(r => r.type === "leave").length, advance: records.filter(r => r.type === "advance").length, date: new Intl.DateTimeFormat("fa-IR", { day: "numeric", month: "short" }).format(new Date(end)) }; }); }, [data.requests, range]);
  const max = Math.max(5, Math.ceil(Math.max(...chart.flatMap(p => [p.leave, p.advance])) / 5) * 5); const x = (i: number) => 49 + i * (516 / (chart.length - 1)); const y = (value: number) => 151 - value / max * 119;
  function path(type: "leave" | "advance") { return chart.map((p, i) => { if (!i) return `M ${x(i)} ${y(p[type])}`; const prev = chart[i - 1]; const mid = (x(i - 1) + x(i)) / 2; return `C ${mid} ${y(prev[type])} ${mid} ${y(p[type])} ${x(i)} ${y(p[type])}`; }).join(" "); }
  return <section className="card trend-card"><div className="card-heading"><div><h2>روند درخواست‌های کارکنان</h2><p>نگاهی به درخواست‌ها در گذر زمان</p></div><select className="small-select" aria-label="بازه زمانی نمودار" value={range} onChange={e => setRange(e.target.value)}><option value="30">۳۰ روز گذشته</option><option value="7">هفته اخیر</option></select></div><div className="chart-legend"><span><i className="dot teal-dot" />مرخصی</span><span><i className="dot sky-dot" />مساعده</span></div><div className="line-chart" dir="ltr"><svg viewBox="0 0 600 187" preserveAspectRatio="none" role="img" aria-label="نمودار روند درخواست‌های مرخصی و مساعده"><defs><linearGradient id="leave-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1aa9a3" stopOpacity=".18" /><stop offset="100%" stopColor="#1aa9a3" stopOpacity=".015" /></linearGradient><linearGradient id="advance-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a6c7db" stopOpacity=".13" /><stop offset="100%" stopColor="#a6c7db" stopOpacity="0" /></linearGradient></defs>{[0, 1, 2, 3, 4].map(i => <g key={i}><line x1="48" y1={y(max / 4 * i)} x2="570" y2={y(max / 4 * i)} stroke="#edf0f3" strokeDasharray="4 5" /><text x="29" y={y(max / 4 * i) + 4} textAnchor="middle" className="chart-axis">{fa(Math.round(max / 4 * i))}</text></g>)}<path d={`${path("advance")} L ${x(chart.length - 1)} 151 L 49 151 Z`} fill="url(#advance-fill)" /><path d={`${path("leave")} L ${x(chart.length - 1)} 151 L 49 151 Z`} fill="url(#leave-fill)" /><path d={path("advance")} fill="none" stroke="#a5c6db" strokeWidth="2.5" strokeLinecap="round" /><path d={path("leave")} fill="none" stroke="#18a29e" strokeWidth="3" strokeLinecap="round" />{chart.map((p, i) => <g key={i} onMouseEnter={() => setHover(i)} onMouseLeave={() => setHover(null)}><rect x={x(i) - 28} y="10" width="56" height="150" fill="transparent" /><circle cx={x(i)} cy={y(p.leave)} r={hover === i ? 5 : 3} fill="white" stroke="#18a29e" strokeWidth="2" /><text x={x(i)} y="177" textAnchor="middle" className="chart-axis">{p.date}</text>{hover === i && <g><rect x={Math.min(480, Math.max(40, x(i) - 49))} y="4" width="100" height="27" rx="7" fill="#203a43" /><text x={Math.min(480, Math.max(40, x(i) - 49)) + 50} y="22" textAnchor="middle" fill="white" fontSize="10">{fa(p.leave)} مرخصی · {fa(p.advance)} مساعده</text></g>}</g>)}</svg></div></section>;
}
function DepartmentChart() {
  const { data, navigate } = useWorkspace(); const colors = ["#19a39e", "#71c5bd", "#a8d8d0", "#b0ccdf"];
  const groups = [...departments].map(name => ({ name, count: data.employees.filter(e => e.department === name).length })).sort((a, b) => b.count - a.count);
  const items = [...groups.slice(0, 3), { name: "سایر واحدها", count: groups.slice(3).reduce((sum, item) => sum + item.count, 0) }]; const total = data.employees.length; let current = 0;
  const gradient = items.map((item, i) => { const start = current; current += item.count / Math.max(1, total) * 360; return `${colors[i]} ${start}deg ${Math.max(start, current - 2)}deg, white ${Math.max(start, current - 2)}deg ${current}deg`; }).join(", ");
  return <section className="card department-card"><div className="card-heading"><div><h2>توزیع کارکنان</h2><p>به تفکیک واحد سازمانی</p></div><button className="icon-button subtle" aria-label="مشاهده گزارش کارکنان" onClick={() => navigate("reports")}><ChartPie size={18} /></button></div><div className="donut-wrap"><div className="donut" style={{ background: total ? `conic-gradient(${gradient})` : "#e7eff0" }}><div className="donut-center"><strong>{fa(total)}</strong><span>همکار در آبان</span></div></div><div className="donut-decor"><span /><span /><span /></div></div><div className="department-legend">{items.map((item, i) => <div key={item.name}><span><i style={{ background: colors[i] }} />{item.name.replace("عملیات و نجات غریق", "عملیات و نجات غریق").replace("اداری و منابع انسانی", "منابع انسانی").replace("خدمات و پشتیبانی", "خدمات و پشتیبانی")}</span><b>{fa(Math.round(item.count / Math.max(1, total) * 100))}<small>٪</small></b></div>)}</div></section>;
}
export function RecentRequests({ records }: { records?: Request[] }) {
  const { data, navigate, setModal } = useWorkspace(); const rows = (records || data.requests).slice(0, 5);
  return <section className="card recent-card"><div className="card-heading"><div className="title-inline"><h2>آخرین درخواست‌ها</h2><span className="count-pill">{fa(data.requests.filter(r => r.status === "pending").length)} جدید</span></div><button className="text-button" onClick={() => navigate("leave")}>مشاهده همه<ArrowLeft size={14} /></button></div>{rows.length ? <div className="table-scroll"><table className="compact-table"><thead><tr><th>کارمند</th><th>نوع درخواست</th><th>تاریخ ثبت</th><th>وضعیت</th><th /></tr></thead><tbody>{rows.map(r => { const e = data.employees.find(e => e.id === r.employeeId); return <tr key={r.id} onClick={() => setModal({ type: "request-detail", request: r })}><td><div className="person-cell"><Avatar employee={e} size="small" /><div><strong>{e?.name || "کارمند"}</strong><small>{e?.position}</small></div></div></td><td><span className={`type-label type-${r.type}`}>{r.type === "leave" ? <CalendarDays size={12} /> : r.type === "ticket" ? <Gift size={12} /> : <Wallet size={12} />}{requestLabels[r.type]}</span></td><td className="muted date-cell">{dateFa(r.createdAt)}</td><td><StatusBadge request={r} /></td><td><button className="table-arrow" aria-label={`بررسی درخواست ${e?.name}`}><ChevronLeft size={16} /></button></td></tr>; })}</tbody></table></div> : <EmptyState title="درخواستی برای بررسی نیست" description="درخواست‌های جدید کارکنان اینجا نمایش داده می‌شوند." />}</section>;
}
export function Dashboard() {
  const { data, navigate, setModal } = useWorkspace(); const employee = data.user.role === "employee"; const admin = data.user.role === "admin"; const finance = admin || data.user.role === "finance"; const period = getPeriod(); const me = data.employees.find(e => e.id === data.user.employeeId); const pending = data.requests.filter(r => r.status === "pending").length; const monthPayrolls = data.payrolls.filter(p => p.month === period); const paid = monthPayrolls.filter(p => p.status === "paid"); const paidTotal = paid.reduce((sum, p) => sum + p.netPay, 0); const usedTickets = data.requests.filter(r => r.type === "ticket" && r.month === period && ["pending", "approved"].includes(r.status)).reduce((sum, r) => sum + r.quantity, 0); const amenityQuota = data.settings.amenities.reduce((sum, a) => sum + a.monthlyLimit, 0); const newStaff = data.employees.filter(e => getPeriod(new Date(e.hireDate)) === period).length;
  const stats = employee ? [
    { label: "مانده مرخصی", value: fa(me?.leaveBalance || 0), unit: "روز", Icon: CalendarDays, color: "teal", detail: "از سهمیه مرخصی سالانه", tag: "در دسترس", page: "leave" as const },
    { label: "درخواست‌های من", value: fa(pending), unit: "در انتظار", Icon: Clock3, color: "orange", detail: "در مسیر بررسی و تأیید", tag: "فعال", page: "leave" as const },
    { label: "امکانات رفاهی باقی‌مانده", value: fa(Math.max(0, amenityQuota - usedTickets)), unit: "مورد", Icon: Gift, color: "blue", detail: `از ${fa(amenityQuota)} مورد در ماه`, tag: "باقی‌مانده", page: "tickets" as const },
    { label: "آخرین حقوق دریافتی", value: new Intl.NumberFormat("fa-IR", { maximumFractionDigits: 1 }).format((paid[0]?.netPay || 0) / 1000000), unit: "میلیون تومان", Icon: Wallet, color: "purple", detail: "فیش حقوقی شما آماده است", tag: "پرداخت شده", page: "payroll" as const }
  ] : [
    { label: "کل کارکنان", value: fa(data.employees.length), unit: "نفر", Icon: Users, color: "teal", detail: "همکار جدید در این ماه", tag: `+${fa(newStaff)}`, page: "employees" as const },
    { label: "درخواست‌های در انتظار", value: fa(pending), unit: "درخواست", Icon: Clock3, color: "orange", detail: "منتظر بررسی و تأیید شما", tag: "نیاز به بررسی", page: "leave" as const },
    { label: "امکانات رفاهی این ماه", value: fa(usedTickets), unit: "مورد", Icon: Gift, color: "blue", detail: "برای لحظه‌های خوش همکاران", tag: "رفاه کارکنان", page: "tickets" as const },
    { label: finance ? "حقوق پرداختی این ماه" : "کارکنان حاضر", value: finance ? new Intl.NumberFormat("fa-IR", { maximumFractionDigits: 1 }).format(paidTotal / 1000000000) : fa(data.employees.filter(e => e.status === "active").length), unit: finance ? "میلیارد تومان" : "نفر", Icon: finance ? Wallet : CalendarCheck2, color: "purple", detail: finance ? "فیش حقوقی پرداخت شده" : "همراهان فعال در مجموعه", tag: finance ? fa(paid.length) : "امروز", page: finance ? "payroll" as const : "employees" as const }
  ];
  return <div className="dashboard page-enter"><PageHeading title={`${admin ? "سلام، آقای محمدی" : `سلام، ${data.user.name.split(" ")[0]}`} 👋`} subtitle="به آبان خوش آمدید؛ امروز هم برای ساختن یک تیم بهتر کنار شما هستیم."><a className="btn secondary" href={`/api/export?type=${employee ? "requests" : "report"}`}><ArrowDownToLine size={16} />دریافت گزارش</a><button className="btn primary" onClick={() => admin ? setModal({ type: "employee" }) : setModal({ type: "request", requestType: "leave" })}><Plus size={17} />{admin ? "افزودن کارمند" : "درخواست جدید"}</button></PageHeading>
    <section className="welcome-banner"><img className="hero-photo" src="/images/waterpark.jpg" alt="نمای هوایی استخرها و سرسره‌های پارک آبی" /><div className="banner-grid" /><div className="banner-content"><div className="banner-kicker"><span />همه‌چیز در یک مسیر روان</div><h2>تیمی هماهنگ، تجربه‌ای بهتر</h2><p>از اولین روز همکاری تا لحظه‌های خوش در آبان؛<br className="mobile-break" /> مدیریت سرمایه انسانی، ساده‌تر از همیشه.</p><button onClick={() => setModal({ type: "help" })}>با امکانات آبان آشنا شوید<ArrowLeft size={14} /></button></div><div className="banner-photo-label"><WavesSmall />پارک آبی آبان<span>جریانِ حالِ خوب</span></div></section>
    <div className="stats-grid">{stats.map(({ label, value, unit, Icon, color, detail, tag, page }) => <button className={`stat-card stat-${color}`} key={label} onClick={() => navigate(page)}><div className="stat-top"><span>{label}</span><div className={`stat-icon ${color}`}><Icon size={20} strokeWidth={1.7} /></div></div><div className="stat-value"><strong>{value}</strong><span>{unit}</span></div><div className="stat-bottom"><span className={`stat-tag ${color}`}>{color === "teal" && !employee ? <ArrowUpRight size={12} /> : null}{tag}</span><small>{detail}</small></div></button>)}</div>
    <GrowthRibbon />
    <div className="dashboard-charts"><RequestsChart />{employee ? <section className="card personal-card"><div className="card-heading"><div><h2>کارت همکار آبان</h2><p>هر روز، بخشی از یک تجربه خوب</p></div><Sparkles size={20} /></div><div className="personal-identity"><Avatar employee={me} size="large" /><h3>{data.user.name}</h3><p>{me?.position}</p></div><div className="personal-meta"><span>کد پرسنلی<strong>{fa(me?.code || 0)}</strong></span><span>واحد سازمانی<strong>{me?.department}</strong></span></div><button className="text-button" onClick={() => navigate("profile")}>مشاهده پروفایل من<ArrowLeft size={14} /></button></section> : <DepartmentChart />}</div>
    <div className="dashboard-bottom"><RecentRequests /><section className="card quick-card"><div className="card-heading"><h2>دسترسی سریع</h2><Zap size={18} className="muted" /></div><div className="quick-grid"><button onClick={() => admin ? setModal({ type: "employee" }) : navigate(employee ? "profile" : "employees")}><span className="quick-icon teal"><Users size={20} strokeWidth={1.6} /></span><span>{admin ? "ثبت کارمند جدید" : employee ? "پروفایل من" : "مشاهده کارکنان"}</span><ArrowUpLeft size={13} /></button><button onClick={() => setModal({ type: "request", requestType: "leave" })}><span className="quick-icon orange"><CalendarDays size={20} strokeWidth={1.6} /></span><span>درخواست مرخصی</span><ArrowUpLeft size={13} /></button><button onClick={() => setModal({ type: "request", requestType: "ticket" })}><span className="quick-icon blue"><Gift size={20} strokeWidth={1.6} /></span><span>درخواست امکانات رفاهی</span><ArrowUpLeft size={13} /></button><button onClick={() => finance ? setModal({ type: "import" }) : setModal({ type: "request", requestType: "advance" })}><span className="quick-icon purple">{finance ? <FileSpreadsheet size={20} strokeWidth={1.6} /> : <CircleDollarSign size={20} strokeWidth={1.6} />}</span><span>{finance ? "بارگذاری حقوق" : "درخواست مساعده"}</span><ArrowUpLeft size={13} /></button></div><div className="payroll-reminder"><div className="reminder-icon"><CalendarCheck2 size={22} strokeWidth={1.6} /></div><div><h3>{finance ? "یک قدم تا پایان پرداخت‌ها" : "فرصتی برای یک حال خوب"}</h3><p>{finance ? `${fa(monthPayrolls.filter(p => p.status === "draft").length)} فیش این ماه در انتظار پرداخت است.` : "سهمیه امکانات رفاهی این ماه را فراموش نکنید."}</p><button onClick={() => navigate(finance || employee ? finance ? "payroll" : "tickets" : "advances")}>{finance ? "بررسی فیش‌های حقوقی" : "مشاهده درخواست‌ها"}<ArrowLeft size={13} /></button></div></div></section></div>
    <section className="card activity-card"><div className="card-heading"><h2>تازه‌ترین فعالیت‌ها</h2><span className="live-label"><i />به‌روز و همگام</span></div><div className="activity-list">{data.events.slice(0, 3).map((event, i) => <button key={event.id} onClick={() => { const request = data.requests.find(r => r.id === event.requestId); if (request) setModal({ type: "request-detail", request }); }}><div className={`activity-symbol ${["teal", "blue", "purple"][i]}`}>{i === 0 ? <CalendarDays size={18} /> : i === 1 ? <Wallet size={18} /> : <Gift size={18} />}</div><div><p><strong>{event.actorName}</strong> {event.action}</p><small>{event.note} <span>·</span> <RelativeTime date={event.createdAt} /></small></div><ChevronLeft size={15} /></button>)}{!data.events.length && <p className="muted">فعالیت‌های جدید شما اینجا ثبت می‌شوند.</p>}</div></section>
    <div className="dashboard-footer"><span>آبان؛ همراه تیم شما در هر موج</span><span><span className="status-dot" />همه اطلاعات به‌روز است</span></div>
  </div>;
}
function WavesSmall() { return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M2 8c4-5 6 5 10 0s6 5 10 0M2 13c4-5 6 5 10 0s6 5 10 0M2 18c4-5 6 5 10 0s6 5 10 0" /></svg>; }
