"use client";
import { useEffect, useId, useRef, useState, type ReactNode } from "react";
import { ArrowLeft, Camera, ChevronLeft, ChevronRight, ImagePlus, Inbox, LoaderCircle, Plus, Trash2, X, ZoomIn, type LucideIcon } from "lucide-react";
import { dateFa, fa, statusLabel, type Employee, type Request } from "@/lib/types";
import { resizeImageFile, ImageInputError } from "@/lib/image-client";
import { JalaliMonthPicker } from "@/components/calendar";
export function Avatar({ employee, name, image, size = "normal" }: { employee?: Pick<Employee, "name" | "avatar">; name?: string; image?: string; size?: "small" | "normal" | "large" }) { const label = employee?.name || name || "کاربر"; const src = employee?.avatar || image; const color = label.charCodeAt(0) % 5; return <span className={`avatar avatar-${size} avatar-color-${color}`}><span>{label.split(" ").slice(0, 2).map(s => s[0]).join(" ")}</span>{src && <img src={src} alt={label} onError={e => { e.currentTarget.style.display = "none"; }} />}</span>; }
export function StatusBadge({ request }: { request: Request }) { return <span className={`badge ${request.status === "pending" ? request.stage === 3 ? "purple" : "amber" : ["approved", "paid"].includes(request.status) ? "green" : request.status === "rejected" ? "red" : "gray"}`}><i />{statusLabel(request)}</span>; }
export function EmployeeBadge({ status }: { status: string }) { return <span className={`badge ${status === "active" ? "green" : status === "on_leave" ? "blue" : status === "candidate" ? "purple" : "gray"}`}><i />{({ active: "فعال", on_leave: "در مرخصی", inactive: "غیرفعال", candidate: "در حال بررسی" } as Record<string, string>)[status]}</span>; }
export function EmptyState({ title = "هنوز اطلاعاتی ثبت نشده", description = "اولین مورد را اضافه کنید تا این بخش جان بگیرد.", action, onAction, icon: Icon = Inbox }: { title?: string; description?: string; action?: string; onAction?: () => void; icon?: LucideIcon }) { return <div className="empty-state"><div className="empty-icon"><Icon size={27} strokeWidth={1.5} /></div><h3>{title}</h3><p>{description}</p>{action && <button className="btn primary" onClick={onAction}>{action}<ArrowLeft size={16} /></button>}</div>; }
export function PageHeading({ title, subtitle, children, eyebrow }: { title: string; subtitle: string; children?: ReactNode; eyebrow?: string }) { return <div className="page-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{subtitle}</p></div><div className="heading-actions">{children}</div></div>; }
export function Field({ label, children, hint, className = "" }: { label: string; children: ReactNode; hint?: string; className?: string }) { return <label className={`field ${className}`}><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
export function Modal({ title, subtitle, children, onClose, wide = false }: { title: string; subtitle?: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  const id = useId(); const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; const oldOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; const root = ref.current; const items = () => Array.from(root?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex="0"]') || []); items()[0]?.focus(); const listener = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); if (event.key === "Tab") { const all = items(); const first = all[0]; const last = all[all.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; document.addEventListener("keydown", listener); return () => { document.body.style.overflow = oldOverflow; document.removeEventListener("keydown", listener); previous?.focus(); }; }, [onClose]);
  return <div className="modal-overlay" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><div className={`modal ${wide ? "modal-wide" : ""}`} ref={ref} role="dialog" aria-modal="true" aria-labelledby={id}><div className="modal-header"><div><h2 id={id}>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="icon-button" onClick={onClose} aria-label="بستن پنجره"><X size={20} /></button></div>{children}</div></div>;
}
export function SubmitButton({ busy, children = "ذخیره تغییرات" }: { busy: boolean; children?: ReactNode }) { return <button className="btn primary" type="submit" disabled={busy}>{busy ? <LoaderCircle size={17} className="spin" /> : null}{busy ? "در حال ذخیره..." : children}</button>; }
export function Pagination({ page, count, pageSize = 10, onChange }: { page: number; count: number; pageSize?: number; onChange: (page: number) => void }) { const total = Math.max(1, Math.ceil(count / pageSize)); const pages = Array.from({ length: total }, (_, i) => i + 1).filter(p => p === 1 || p === total || Math.abs(p - page) <= 1); return <div className="pagination"><span>{count ? `نمایش ${fa((page - 1) * pageSize + 1)} تا ${fa(Math.min(page * pageSize, count))} از ${fa(count)} مورد` : "۰ مورد"}</span><div><button disabled={page <= 1} onClick={() => onChange(page - 1)} aria-label="صفحه قبل"><ChevronRight size={17} /></button>{pages.map((p, i) => <span key={p} className="page-number-wrap">{i > 0 && p - pages[i - 1] > 1 && <span className="ellipsis">…</span>}<button className={page === p ? "selected" : ""} onClick={() => onChange(p)}>{fa(p)}</button></span>)}<button disabled={page >= total} onClick={() => onChange(page + 1)} aria-label="صفحه بعد"><ChevronLeft size={17} /></button></div></div>; }
/** Persian year/month popover picker; keeps the historic `PeriodSelect` name so every call site keeps working unchanged. */
export function PeriodSelect({ value, onChange }: { value: string; onChange: (period: string) => void }) { return <JalaliMonthPicker value={value} onChange={onChange} ariaLabel="انتخاب ماه حقوق" />; }
export function RelativeTime({ date }: { date: string }) { const minutes = Math.max(1, Math.floor((Date.now() - new Date(date).getTime()) / 60000)); return <span>{minutes < 60 ? `${fa(minutes)} دقیقه پیش` : minutes < 1440 ? `${fa(Math.floor(minutes / 60))} ساعت پیش` : dateFa(date)}</span>; }

export function ImageLightbox({ src, onClose }: { src: string; onClose: () => void }) {
  useEffect(() => { const handler = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [onClose]);
  return <div className="image-lightbox" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><button aria-label="بستن نمایش تصویر" onClick={onClose}><X size={20} /></button><img src={src} alt="مشاهده بزرگ‌نمای مدرک" /></div>;
}

/** Reads, downscales and previews a single image (personal photo, national ID front/back). */
export function ImageUploadField({ label, value, onChange, round = false, hint }: { label: string; value: string; onChange: (dataUri: string) => void; round?: boolean; hint?: string }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [zoom, setZoom] = useState(false); const input = useRef<HTMLInputElement>(null);
  async function handle(file?: File) { if (!file) return; setBusy(true); setError(""); try { onChange(await resizeImageFile(file)); } catch (e) { setError(e instanceof ImageInputError ? e.message : "بارگذاری تصویر ناموفق بود."); } finally { setBusy(false); if (input.current) input.current.value = ""; } }
  return <Field label={label} hint={hint}>
    {round ? <div className="upload-avatar-row"><div className="upload-avatar-preview">{value ? <img src={value} alt={label} /> : <Camera size={26} />}</div><div className="upload-avatar-actions"><button type="button" className="btn small secondary" disabled={busy} onClick={() => input.current?.click()}>{busy ? <LoaderCircle size={14} className="spin" /> : <ImagePlus size={14} />}{value ? "تغییر تصویر" : "انتخاب تصویر"}</button>{value && <button type="button" className="btn small danger-soft" onClick={() => onChange("")}><Trash2 size={13} />حذف</button>}</div></div>
      : <button type="button" className={`doc-upload-card ${value ? "has-image" : ""}`} onClick={() => value ? setZoom(true) : input.current?.click()}>{value ? <><img src={value} alt={label} />{busy ? <LoaderCircle size={18} className="spin" /> : <span className="doc-upload-label"><ZoomIn size={13} />مشاهده بزرگ‌نما</span>}<span className="doc-remove" role="button" aria-label={`حذف ${label}`} onClick={e => { e.stopPropagation(); onChange(""); }}><Trash2 size={13} /></span></> : busy ? <LoaderCircle size={20} className="spin" /> : <><ImagePlus size={22} /><span className="doc-upload-label">{label}</span></>}</button>}
    <input ref={input} type="file" accept="image/jpeg,image/png" className="hidden-file-input" onChange={e => handle(e.target.files?.[0])} />
    {error && <small className="upload-error">{error}</small>}
    {zoom && value && <ImageLightbox src={value} onClose={() => setZoom(false)} />}
  </Field>;
}

/** Multi-file uploader for identity documents (شناسنامه / گذرنامه pages). */
export function DocumentPagesField({ label, values, onChange, max = 6 }: { label: string; values: string[]; onChange: (values: string[]) => void; max?: number }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [zoom, setZoom] = useState<string | null>(null); const input = useRef<HTMLInputElement>(null);
  async function handle(files: FileList | null) { if (!files || !files.length) return; setBusy(true); setError(""); try { const remaining = max - values.length; const selected = Array.from(files).slice(0, Math.max(0, remaining)); if (files.length > remaining) setError(`حداکثر ${fa(max)} صفحه قابل بارگذاری است.`); const added = await Promise.all(selected.map(file => resizeImageFile(file))); onChange([...values, ...added]); } catch (e) { setError(e instanceof ImageInputError ? e.message : "بارگذاری تصویر ناموفق بود."); } finally { setBusy(false); if (input.current) input.current.value = ""; } }
  return <Field label={label} hint={`حداکثر ${fa(max)} صفحه؛ JPEG یا PNG`}>
    <div className="doc-pages-grid">{values.map((page, i) => <div className="doc-page-tile" key={i}><img src={page} alt={`صفحه ${i + 1}`} onClick={() => setZoom(page)} role="button" /><span className="doc-remove" role="button" aria-label={`حذف صفحه ${i + 1}`} onClick={() => onChange(values.filter((_, index) => index !== i))}><Trash2 size={13} /></span></div>)}{values.length < max && <button type="button" className="doc-page-add" onClick={() => input.current?.click()} disabled={busy}>{busy ? <LoaderCircle size={18} className="spin" /> : <Plus size={18} />}<span>افزودن صفحه</span></button>}</div>
    <input ref={input} type="file" accept="image/jpeg,image/png" multiple className="hidden-file-input" onChange={e => handle(e.target.files)} />
    {error && <small className="upload-error">{error}</small>}
    {zoom && <ImageLightbox src={zoom} onClose={() => setZoom(null)} />}
  </Field>;
}
