import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const errors = [];
const baseURL = process.env.TEST_BASE_URL || 'http://localhost:3000';
const context = await browser.newContext({ viewport: { width: 1440, height: 1024 }, deviceScaleFactor: 1 });
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.status() >= 500) errors.push(`${response.status()} ${response.url()}`); });
async function settle() { await page.evaluate(() => document.fonts.ready); await page.waitForTimeout(250); }
async function navigate(name) { await page.locator('.main-nav').getByRole('button', { name: new RegExp(`^${name}`) }).click(); await page.waitForTimeout(200); }
try {
  await page.goto(baseURL, { waitUntil: 'networkidle' });
  await page.getByRole('heading', { name: 'سلام، آقای محمدی 👋' }).waitFor();
  await settle();
  await page.screenshot({ path: 'artifacts/dashboard-desktop.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  console.log('PASS Desktop dashboard, font, image and responsive bounds');
  await navigate('مدیریت کارکنان');
  await page.getByRole('heading', { name: 'فهرست کارکنان' }).waitFor();
  await page.getByRole('textbox', { name: 'جستجوی کارکنان' }).fill('سارا رحیمی');
  await page.getByRole('button', { name: 'پروفایل سارا رحیمی' }).waitFor();
  await page.getByRole('textbox', { name: 'جستجوی کارکنان' }).fill('');
  await page.screenshot({ path: 'artifacts/employees-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'افزودن کارمند', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('نام و نام خانوادگی *').fill('آزمون رابط کاربری');
  await dialog.getByLabel('عنوان شغلی *').fill('کارشناس آزمون رابط');
  await dialog.getByLabel('ایمیل ورود *').fill('ui-smoke-check@aban.test');
  await dialog.getByLabel('رمز عبور اولیه *', { exact: false }).fill('UiSmoke@2026');
  await page.screenshot({ path: 'artifacts/employee-form.png', fullPage: true });
  await dialog.getByRole('button', { name: 'ایجاد پرونده و حساب کاربری' }).click();
  await dialog.waitFor({ state: 'hidden' });
  await page.getByRole('textbox', { name: 'جستجوی کارکنان' }).fill('آزمون رابط کاربری');
  await page.getByRole('button', { name: 'ویرایش آزمون رابط کاربری', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('شماره تماس').fill('09129999999');
  await dialog.getByRole('button', { name: 'ذخیره تغییرات', exact: true }).click();
  await dialog.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'حذف آزمون رابط کاربری', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'بله، حذف شود' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('heading', { name: 'همکاری با این مشخصات پیدا نشد' }).waitFor();
  console.log('PASS Browser employee create, edit, delete, search and empty state');
  await navigate('درخواست‌های مرخصی');
  await page.locator('.table-review').first().click();
  await page.getByRole('dialog').waitFor();
  assert.ok(await page.locator('.workflow-step').count() >= 3);
  await page.screenshot({ path: 'artifacts/request-workflow.png', fullPage: true });
  await page.keyboard.press('Escape');
  await navigate('حقوق و دستمزد');
  await page.getByRole('heading', { name: 'حقوق و دستمزد', exact: true }).waitFor();
  await page.screenshot({ path: 'artifacts/payroll-desktop.png', fullPage: true });
  await page.getByRole('button', { name: /^فیش حقوقی / }).first().click();
  await page.locator('.payslip').waitFor();
  await page.screenshot({ path: 'artifacts/payslip.png', fullPage: true });
  await page.emulateMedia({ media: 'print' });
  assert.equal(await page.locator('.payslip').evaluate(e => getComputedStyle(e).visibility), 'visible');
  await page.pdf({ path: 'artifacts/payslip.pdf', format: 'A4', printBackground: true });
  await page.emulateMedia({ media: 'screen' });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'ورود کارکرد از اکسل' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: /فایل الگوی کارکرد/ }).click();
  const download = await downloadPromise;
  assert.ok(download.suggestedFilename().endsWith('.xlsx'));
  await page.keyboard.press('Escape');
  console.log('PASS Approval workflow dialog, payroll preview, printable PDF and Excel template');
  await page.getByRole('button', { name: 'تغییر حساب کاربری' }).click();
  await page.locator('.account-popover').getByRole('button', { name: 'کارمند نمایشی', exact: true }).click();
  await page.getByRole('heading', { name: 'سلام، سارا 👋' }).waitFor();
  assert.equal(await page.locator('.main-nav').getByRole('button', { name: 'مدیریت کارکنان', exact: true }).count(), 0);
  await page.screenshot({ path: 'artifacts/employee-dashboard.png', fullPage: true });
  console.log('PASS Employee dashboard and role-specific navigation');
  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  await mobileContext.request.post(`${baseURL}/api/auth/demo`, { data: { role: 'admin' } });
  const mobile = await mobileContext.newPage();
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto(baseURL, { waitUntil: 'networkidle' });
  await mobile.getByRole('heading', { name: 'سلام، آقای محمدی 👋' }).waitFor();
  await mobile.evaluate(() => document.fonts.ready);
  await mobile.screenshot({ path: 'artifacts/dashboard-mobile.png', fullPage: true });
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mobile.getByRole('button', { name: 'باز کردن منو' }).click();
  await mobile.locator('.main-nav').getByRole('button', { name: 'مدیریت کارکنان', exact: true }).click();
  await mobile.getByRole('heading', { name: 'فهرست کارکنان' }).waitFor();
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mobile.screenshot({ path: 'artifacts/employees-mobile.png', fullPage: true });
  await mobile.goto(`${baseURL}/login`);
  await mobile.screenshot({ path: 'artifacts/login-mobile.png', fullPage: true });
  await page.goto(`${baseURL}/login`);
  await page.getByRole('heading', { name: 'دوباره به آبان خوش آمدید' }).waitFor();
  await page.screenshot({ path: 'artifacts/login-desktop.png', fullPage: true });
  await page.getByLabel('نشانی ایمیل').fill('invalid@aban.test');
  await page.getByLabel('رمز عبور', { exact: true }).fill('Wrong@2026');
  await page.getByRole('button', { name: 'ورود به فضای کاری', exact: true }).click();
  await page.getByRole('alert').waitFor();
  console.log('PASS Mobile layout, drawer navigation, login and authentication error states');
  assert.deepEqual(errors, []);
  console.log('ALL BROWSER CHECKS PASSED; screenshots saved in artifacts/');
} finally {
  const cleanup = await context.request.post(`${baseURL}/api/auth/demo`, { data: { role: 'admin' } });
  if (cleanup.ok()) { const data = await (await context.request.get(`${baseURL}/api/workspace`)).json(); const leftover = data.employees?.find(e => e.email === 'ui-smoke-check@aban.test'); if (leftover) await context.request.post(`${baseURL}/api/workspace`, { data: { action: 'employee.delete', data: { id: leftover.id } } }); }
  await browser.close();
}
