import 'dotenv/config';
import assert from 'node:assert/strict';
import { request } from '@playwright/test';
import database from '@/db';
import schema from '@/db/schema';
const { db } = database;
const { jobs, employees, courses, surveys, onboardingTemplates, salaryScenarios, talentEvents } = schema;
import { eq, like, inArray } from 'drizzle-orm';

const baseURL = process.env.TEST_BASE_URL || 'http://localhost:3000';
const contexts = [];
const prefix = `QA-TALENT-${Date.now()}`;
const fixture = { employeeIds: [], jobIds: [], courseIds: [], surveyIds: [], templateIds: [], scenarioIds: [] };
async function context() { const c = await request.newContext({ baseURL }); contexts.push(c); return c; }
async function json(response, status = 200) { const body = await response.json(); assert.equal(response.status(), status, JSON.stringify(body)); return body; }
const act = async (c, action, data, status = 200) => json(await c.post('/api/talent', { data: { action, data } }), status);
const read = async c => json(await c.get('/api/talent'));
const workspace = async c => json(await c.get('/api/workspace'));
const date = n => new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);
const admin = await context(); const manager = await context(); const finance = await context(); const guest = await context();
let baseline;
try {
  await json(await guest.get('/api/talent'), 401);
  for (const [c, role] of [[admin,'admin'],[manager,'manager'],[finance,'finance']]) await json(await c.post('/api/auth/demo', { data: { role } }));
  baseline = await workspace(admin);
  const initial = await read(admin);
  assert.ok(initial.jobs.length >= 6 && initial.courses.length >= 3 && initial.surveys.length >= 2);
  assert.ok(!('content' in (initial.files[0] || {})));
  assert.equal((await read(finance)).applicants.length, 0);
  const managerWorkspace = await workspace(manager); const department = managerWorkspace.employees[0].department;
  assert.ok((await read(manager)).jobs.every(j => j.department === department));
  await act(finance, 'job.delete', { id: initial.jobs[0].id }, 403);
  console.log('PASS talent data seed and role-scoped confidential resources');

  const jobInput = { title: `${prefix} فرصت`, department, location: 'آبان', contract: 'تمام‌وقت', description: 'شرح شغل آزمایشی', requirements: 'آزمون نرم‌افزار', status: 'open', openings: 2, salaryMin: 18000000, salaryMax: 30000000, hiringCost: 500000, deadline: date(15) };
  await act(admin, 'job.save', jobInput);
  const job = (await read(admin)).jobs.find(j => j.title === jobInput.title); fixture.jobIds.push(job.id);
  await act(manager, 'job.save', { ...job, title: `${prefix} فرصت ویرایش` });
  const publicJobs = await json(await guest.get('/api/careers'));
  assert.ok(publicJobs.jobs.some(j => j.id === job.id));
  assert.ok(publicJobs.jobs.every(j => !('hiringCost' in j)));
  await json(await guest.post('/api/careers', { multipart: { jobId: job.id, name: 'بدون رضایت', email: 'no-consent@example.test', phone: '09120000000' } }), 400);
  const candidateEmail = `talent-${Date.now()}@example.test`;
  const pdf = Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF');
  const submission = await json(await guest.post('/api/careers', { multipart: { jobId: job.id, name: `${prefix} همکار`, email: candidateEmail, phone: '09121111111', experience: '3', skills: 'همکاری تیمی', consent: 'true', file: { name: 'resume.pdf', mimeType: 'application/pdf', buffer: pdf } } }));
  assert.ok(submission.trackingCode);
  await json(await guest.post('/api/careers', { multipart: { jobId: job.id, name: `${prefix} تکراری`, email: candidateEmail, phone: '09121111111', consent: 'true' } }), 409);
  let talent = await read(admin); let candidate = talent.applicants.find(c => c.email === candidateEmail);
  const file = talent.files.find(f => f.applicantId === candidate.id);
  await json(await guest.get(`/api/talent/files?id=${file.id}`), 403);
  const downloaded = await manager.get(`/api/talent/files?id=${file.id}`); assert.equal(downloaded.status(), 200); assert.deepEqual(await downloaded.body(), pdf);
  await act(manager, 'applicant.note', { id: candidate.id, kind: 'evaluation', body: 'ارزیابی اولیه مثبت', score: 4 });
  await act(admin, 'applicant.note', { id: candidate.id, kind: 'evaluation', body: 'ارزیابی دوم', score: 2 });
  candidate = (await read(admin)).applicants.find(c => c.id === candidate.id); assert.equal(candidate.rating, 3);
  await act(manager, 'applicant.move', { id: candidate.id, fromStage: 'new', stage: 'screening' });
  await act(manager, 'applicant.move', { id: candidate.id, fromStage: 'new', stage: 'offer' }, 409);
  console.log('PASS public careers, consent, duplicate control, protected PDF and team evaluation');

  const interviewerId = managerWorkspace.user.employeeId;
  const interviewInput = { applicantId: candidate.id, interviewerId, startsAt: `${date(70)}T10:00:00Z`, duration: 45, mode: 'حضوری', location: 'اتاق آزمون', status: 'scheduled', feedback: '', score: 0 };
  await act(manager, 'interview.save', interviewInput);
  const meeting = (await read(admin)).interviews.find(i => i.applicantId === candidate.id);
  await act(manager, 'interview.save', interviewInput, 400);
  const ics = await manager.get(`/api/talent/export?type=calendar&id=${meeting.id}`); assert.equal(ics.status(), 200); assert.ok((await ics.text()).includes('BEGIN:VEVENT'));
  await act(manager, 'interview.save', { ...interviewInput, id: meeting.id, status: 'completed', feedback: 'مناسب همکاری', score: 4 });
  console.log('PASS interview scheduling, collision protection, feedback and calendar export');

  await act(admin, 'template.save', { title: `${prefix} الگو`, department: 'all', welcome: 'به تیم آزمایش خوش آمدید.', tasks: [{ title: 'مطالعه راهنما', ownerRole: 'employee', offsetDays: 1 }, { title: 'تأیید مدیر', ownerRole: 'manager', offsetDays: 2 }, { title: 'تحویل مدارک', ownerRole: 'admin', offsetDays: 0 }] });
  const template = (await read(admin)).templates.find(t => t.title === `${prefix} الگو`); fixture.templateIds.push(template.id);
  await act(manager, 'applicant.move', { id: candidate.id, stage: 'offer' });
  await act(manager, 'applicant.hire', { id: candidate.id }, 403);
  const hired = await act(admin, 'applicant.hire', { id: candidate.id, code: 'QA900001', baseSalary: 20000001, hireDate: date(0), password: 'Talent@2026', templateId: template.id }); fixture.employeeIds.push(hired.employeeId);
  await act(admin, 'applicant.hire', { id: candidate.id, code: 'QA900002', baseSalary: 20000000, hireDate: date(0), password: 'Talent@2026' }, 409);
  const employee = await context(); await json(await employee.post('/api/auth/login', { data: { email: candidateEmail, password: 'Talent@2026' } }));
  const employeeTalent = await read(employee); assert.equal(employeeTalent.applicants.length, 0); assert.equal(employeeTalent.policies.length, 0);
  const plan = employeeTalent.plans.find(p => p.employeeId === hired.employeeId); assert.ok(plan);
  const tasks = employeeTalent.tasks.filter(t => t.planId === plan.id); assert.equal(tasks.length, 3);
  await act(employee, 'task.toggle', { id: tasks.find(t => t.ownerRole === 'admin').id, done: true }, 403);
  await act(employee, 'task.toggle', { id: tasks.find(t => t.ownerRole === 'employee').id, done: true });
  await act(manager, 'task.toggle', { id: tasks.find(t => t.ownerRole === 'manager').id, done: true });
  await act(admin, 'task.toggle', { id: tasks.find(t => t.ownerRole === 'admin').id, done: true });
  assert.ok((await read(employee)).tasks.every(t => t.done));
  await act(admin, 'template.save', { ...template, title: `${prefix} الگوی جدید` });
  assert.equal((await read(employee)).plans[0].title, `${prefix} الگو`);
  await act(admin, 'job.delete', { id: job.id }, 400);
  console.log('PASS transactional hire, employee login, onboarding roles and template snapshot isolation');

  const courseInput = { title: `${prefix} دوره`, category: 'داخلی', instructor: 'مدرس آزمون', description: 'دوره آزمایشی', level: 'مقدماتی', status: 'published', passScore: 70, lessons: [{ id: 'lesson1', title: 'درس اول', content: 'مطالعه کامل', minutes: 10, url: '' }], quiz: [{ id: 'quiz1', text: 'گزینه درست کدام است؟', options: ['درست', 'نادرست'], correct: 0 }] };
  await act(admin, 'course.save', courseInput); let course = (await read(admin)).courses.find(c => c.title === courseInput.title); fixture.courseIds.push(course.id);
  await act(admin, 'enrollment.assign', { courseId: course.id, employeeIds: [hired.employeeId], dueDate: date(10) });
  const training = await read(employee); const enrollment = training.enrollments.find(e => e.courseId === course.id); assert.ok(enrollment); assert.equal(training.courses.find(c => c.id === course.id).quiz[0].correct, undefined);
  await act(employee, 'enrollment.quiz', { id: enrollment.id, answers: { quiz1: 0 } }, 400);
  await act(employee, 'enrollment.lesson', { id: enrollment.id, lessonId: 'lesson1' });
  const failed = await act(employee, 'enrollment.quiz', { id: enrollment.id, answers: { quiz1: 1 } }); assert.equal(failed.passed, false); assert.equal(failed.score, 0);
  const passed = await act(employee, 'enrollment.quiz', { id: enrollment.id, answers: { quiz1: 0 } }); assert.equal(passed.passed, true); assert.equal(passed.score, 100);
  await act(admin, 'course.save', { ...course, description: 'توضیح ویرایش‌شده' });
  await act(admin, 'course.save', { ...course, lessons: [{ ...course.lessons[0], content: 'محتوای تغییر یافته' }] }, 400);
  await act(employee, 'enrollment.quiz', { id: enrollment.id, answers: { quiz1: 0 } }, 409);
  await act(admin, 'course.save', { ...course, status: 'archived' });
  const archivedCourse = (await read(employee)).courses.find(c => c.id === course.id);
  assert.equal(archivedCourse?.status, 'archived');
  assert.equal(archivedCourse?.quiz[0].correct, undefined);
  await act(admin, 'enrollment.assign', { courseId: course.id, employeeIds: [hired.employeeId], dueDate: date(10) }, 400);
  console.log('PASS private answer keys, server grading, immutable course content and archived transcripts');

  const respondents = [employee];
  for (let index = 0; index < 4; index++) { const email = `${prefix}-${index}@example.test`; await json(await admin.post('/api/workspace', { data: { action: 'employee.save', data: { name: `${prefix} پاسخ‌دهنده ${index}`, code: `QA90100${index}`, email, password: 'Talent@2026', department, position: 'آزمایشی', hireDate: date(0), baseSalary: 18000000, status: 'active', leaveBalance: 26 } } })); const e = (await workspace(admin)).employees.find(e => e.email === email.toLowerCase()); fixture.employeeIds.push(e.id); const c = await context(); await json(await c.post('/api/auth/login', { data: { email, password: 'Talent@2026' } })); respondents.push(c); }
  const surveyInput = { title: `${prefix} نبض`, description: 'نظرسنجی آزمایشی', department, deadline: date(10), questions: [{ id: 'satisfaction', text: 'راضی هستم', type: 'scale', dimension: 'رضایت' }, { id: 'enps', text: 'توصیه می‌کنم', type: 'enps', dimension: 'توصیه' }] };
  await act(admin, 'survey.save', surveyInput); const survey = (await read(admin)).surveys.find(s => s.title === surveyInput.title); fixture.surveyIds.push(survey.id);
  await act(admin, 'survey.publish', { id: survey.id });
  await act(admin, 'survey.save', { ...survey, title: 'ویرایش غیرمجاز پس از انتشار' }, 400);
  for (const c of respondents) await act(c, 'survey.respond', { id: survey.id, answers: { satisfaction: 5, enps: 10 } });
  await act(employee, 'survey.respond', { id: survey.id, answers: { satisfaction: 5, enps: 10 } }, 409);
  let metrics = (await read(admin)).metrics.find(m => m.surveyId === survey.id); assert.equal(metrics.responses, 5); assert.equal(metrics.reportReady, false); assert.equal(metrics.score, null);
  await act(admin, 'survey.close', { id: survey.id });
  metrics = (await read(admin)).metrics.find(m => m.surveyId === survey.id); assert.equal(metrics.reportReady, true); assert.equal(metrics.score, 100); assert.equal(metrics.enps, 100);
  const audienceBeforeDeletion = metrics.audience;
  const deletedRespondent = fixture.employeeIds[fixture.employeeIds.length - 1];
  await json(await admin.post('/api/workspace', { data: { action: 'employee.delete', data: { id: deletedRespondent } } }));
  const retainedMetrics = (await read(admin)).metrics.find(m => m.surveyId === survey.id);
  assert.equal(retainedMetrics.audience, audienceBeforeDeletion);
  assert.equal(retainedMetrics.responses, 5);
  assert.equal(retainedMetrics.score, 100);
  assert.equal(retainedMetrics.eligible, false);
  assert.ok(metrics.departments.filter(d => d.count < 5).every(d => d.score === null));
  const personalReport = (await read(employee)).metrics.find(m => m.surveyId === survey.id); assert.equal(personalReport.reportReady, false); assert.equal(personalReport.score, null); assert.equal(personalReport.participated, true);
  await act(manager, 'improvement.save', { surveyId: survey.id, title: `${prefix} اقدام`, employeeId: hired.employeeId, dueDate: date(5), status: 'in_progress', notes: 'اقدام آزمایشی' });
  const improvement = (await read(manager)).improvements.find(i => i.title === `${prefix} اقدام`); assert.ok(improvement); await act(manager, 'improvement.save', { ...improvement, status: 'done' });
  console.log('PASS survey snapshots, duplicate prevention, threshold privacy, eNPS and follow-up actions');

  const sim = await act(finance, 'salary.simulate', { title: `${prefix} سناریو`, department, employeeId: hired.employeeId }); fixture.scenarioIds.push(sim.scenarioId);
  const scenario = (await read(finance)).scenarios.find(s => s.id === sim.scenarioId); assert.equal(scenario.entries.length, 1); assert.ok(scenario.entries[0].proposed >= 20000001);
  await act(finance, 'salary.apply', { id: scenario.id }, 403);
  const e = (await workspace(admin)).employees.find(e => e.id === hired.employeeId);
  await json(await admin.post('/api/workspace', { data: { action: 'employee.save', data: { ...e, baseSalary: e.baseSalary + 1 } } }));
  await act(admin, 'salary.apply', { id: scenario.id }, 409);
  await json(await admin.post('/api/workspace', { data: { action: 'employee.save', data: e } }));
  await act(admin, 'salary.apply', { id: scenario.id });
  assert.equal((await workspace(employee)).employees[0].baseSalary, scenario.entries[0].proposed);
  await act(admin, 'salary.apply', { id: scenario.id }, 409);
  await act(admin, 'salary.delete', { id: scenario.id }, 409);
  assert.equal((await finance.get(`/api/talent/export?type=compensation&id=${scenario.id}`)).status(), 200);
  await json(await employee.get(`/api/talent/export?type=compensation&id=${scenario.id}`), 403);
  console.log('PASS individual salary simulation, stale-state rejection, manager approval and protected export');
  console.log('ALL TALENT WORKFLOW CHECKS PASSED');
} finally {
  // Test-only cleanup uses Drizzle and tracked fixture IDs, never blanket deletion.
  if (fixture.scenarioIds.length) await db.delete(salaryScenarios).where(inArray(salaryScenarios.id, fixture.scenarioIds));
  if (fixture.surveyIds.length) await db.delete(surveys).where(inArray(surveys.id, fixture.surveyIds));
  if (fixture.jobIds.length) await db.delete(jobs).where(inArray(jobs.id, fixture.jobIds));
  if (fixture.courseIds.length) await db.delete(courses).where(inArray(courses.id, fixture.courseIds));
  if (fixture.employeeIds.length) await db.delete(employees).where(inArray(employees.id, fixture.employeeIds));
  if (fixture.templateIds.length) await db.delete(onboardingTemplates).where(inArray(onboardingTemplates.id, fixture.templateIds));
  await db.delete(talentEvents).where(like(talentEvents.title, `%${prefix}%`));
  if (baseline) assert.equal((await workspace(admin)).employees.length, baseline.employees.length);
  await Promise.all(contexts.map(c => c.dispose()));
  console.log('Temporary test fixtures removed; existing employee records preserved.');
  process.exitCode = process.exitCode || 0;
}
